export const exchanges = [
	'AMEX', // New York Stock Exchange Arca
	'CBOE', // Chicago Board Options Exchange
	// 'HKSE', // Hong Kong Stock Exchange
	// 'JPX', // Tokyo Stock Exchange
	// 'LSE', // London Stock Exchange
	'NASDAQ', // NASDAQ Capital Market
	'NYSE', // New York Stock Exchange
	// 'SHH', // Shanghai Stock Exchange
	// 'SHZ', // Shenzhen Stock Exchange
	// 'TSX', // Toronto Stock Exchange
]

export const map = {
	AMEX: 'New York Stock Exchange Arca',
	AMS: 'Euronext Amsterdam',
	AQS: 'Aquis AQSE',
	ASX: 'Australian Securities Exchange',
	ATH: 'Athens Stock Exchange',
	BER: 'Berlin Stock Exchange',
	BME: 'Madrid Stock Exchange',
	BRU: 'Euronext Brussels',
	BSE: 'Bombay Stock Exchange',
	BUD: 'Budapest Stock Exchange',
	BUE: 'Buenos Aires Stock Exchange',
	BVC: 'Colombia Stock Exchange',
	CBOE: 'Chicago Board Options Exchange',
	CNQ: 'Canadian Securities Exchange',
	CPH: 'NASDAQ Copenhagen',
	DFM: 'Dubai Financial Market',
	DOH: 'Qatar Stock Exchange',
	DUB: 'Euronext Dublin',
	DUS: 'Dusseldorf Stock Exchange',
	DXE: 'Cboe Europe',
	EGX: 'Egyptian Exchange',
	HAM: 'Hamburg Stock Exchange',
	HEL: 'NASDAQ Helsinki',
	HKSE: 'Hong Kong Stock Exchange',
	HOSE: 'Ho Chi Minh Stock Exchange',
	ICE: 'NASDAQ Iceland',
	IOB: 'International Order Book',
	IST: 'Istanbul Stock Exchange',
	JKT: 'Jakarta Stock Exchange',
	JNB: 'Johannesburg Stock Exchange',
	JPX: 'Tokyo Stock Exchange',
	KLS: 'Malaysian Stock Exchange',
	KOE: 'KOSDAQ',
	KSC: 'Korea Exchange',
	KUW: 'Kuwait Stock Exchange',
	LIS: 'Euronext Lisbon',
	LSE: 'London Stock Exchange',
	MCX: 'Moscow Stock Exchange',
	MEX: 'Mexican Stock Exchange',
	MIL: 'Italian Stock Exchange',
	MUN: 'Munich Stock Exchange',
	NASDAQ: 'NASDAQ Capital Market',
	NEO: 'CBOE CA',
	NSE: 'National Stock Exchange of India',
	NYSE: 'New York Stock Exchange',
	NZE: 'New Zealand Exchange',
	OEM: 'OTC Markets EXMKT',
	OSL: 'Oslo Stock Exchange',
	OTC: 'Other OTC',
	PAR: 'Euronext Paris',
	PRA: 'Prague Stock Exchange',
	RIS: 'NASDAQ Riga',
	SAO: 'B3 S.A.',
	SAU: 'Saudi Exchange',
	SES: 'Stock Exchange of Singapore',
	SET: 'Stock Exchange of Thailand',
	SGO: 'Santiago Stock Exchange',
	SHH: 'Shanghai Stock Exchange',
	SHZ: 'Shenzhen Stock Exchange',
	SIX: 'Swiss Exchange',
	STO: 'Stockholm Stock Exchange',
	STU: 'Stuttgart Stock Exchange',
	TAI: 'Taiwan Stock Exchange',
	TAL: 'NASDAQ Tallinn',
	TLV: 'Tel Aviv Stock Exchange',
	TSX: 'Toronto Stock Exchange',
	TSXV: 'Toronto Stock Exchange Ventures',
	TWO: 'Taipei Exchange',
	VIE: 'Vienna Stock Exchange',
	WSE: 'Warsaw Stock Exchange',
	XETRA: 'Frankfurt Stock Exchange',
}
