import type * as api from '../api.js'

const companyProfile = [
	'symbol',
	'price',
	'marketCap',
	'beta',
	'lastDividend',
	'range',
	'change',
	'changePercentage',
	'volume',
	'averageVolume',
	'companyName',
	'currency',
	'cik',
	'isin',
	'cusip',
	'exchangeFullName',
	'exchange',
	'industry',
	'website',
	'description',
	'ceo',
	'sector',
	'country',
	'fullTimeEmployees',
	'phone',
	'address',
	'city',
	'state',
	'zip',
	// 'image',
	'ipoDate',
	// 'defaultImage',
	'isEtf',
	'isActivelyTrading',
	'isAdr',
	'isFund',
] as const

const incomeStatement = [
	'revenue',
	'costOfRevenue',
	'grossProfit',
	'researchAndDevelopmentExpenses',
	'generalAndAdministrativeExpenses',
	'sellingAndMarketingExpenses',
	'sellingGeneralAndAdministrativeExpenses',
	'otherExpenses',
	'operatingExpenses',
	'costAndExpenses',
	'netInterestIncome',
	'interestIncome',
	'interestExpense',
	'depreciationAndAmortization',
	'ebitda',
	'ebit',
	'nonOperatingIncomeExcludingInterest',
	'operatingIncome',
	'totalOtherIncomeExpensesNet',
	'incomeBeforeTax',
	'incomeTaxExpense',
	'netIncomeFromContinuingOperations',
	'netIncomeFromDiscontinuedOperations',
	'otherAdjustmentsToNetIncome',
	'netIncome',
	'netIncomeDeductions',
	'bottomLineNetIncome',
	'eps',
	'epsDiluted',
	'weightedAverageShsOut',
	'weightedAverageShsOutDil',
] as const

const balanceSheetStatement = [
	'cashAndCashEquivalents',
	'shortTermInvestments',
	'cashAndShortTermInvestments',
	'netReceivables',
	'accountsReceivables',
	'otherReceivables',
	'inventory',
	'prepaids',
	'otherCurrentAssets',
	'totalCurrentAssets',
	'propertyPlantEquipmentNet',
	'goodwill',
	'intangibleAssets',
	'goodwillAndIntangibleAssets',
	'longTermInvestments',
	'taxAssets',
	'otherNonCurrentAssets',
	'totalNonCurrentAssets',
	'otherAssets',
	'totalAssets',
	'totalPayables',
	'accountPayables',
	'otherPayables',
	'accruedExpenses',
	'shortTermDebt',
	'capitalLeaseObligationsCurrent',
	'taxPayables',
	'deferredRevenue',
	'otherCurrentLiabilities',
	'totalCurrentLiabilities',
	'longTermDebt',
	'deferredRevenueNonCurrent',
	'deferredTaxLiabilitiesNonCurrent',
	'otherNonCurrentLiabilities',
	'totalNonCurrentLiabilities',
	'otherLiabilities',
	'capitalLeaseObligations',
	'totalLiabilities',
	'treasuryStock',
	'preferredStock',
	'commonStock',
	'retainedEarnings',
	'additionalPaidInCapital',
	'accumulatedOtherComprehensiveIncomeLoss',
	'otherTotalStockholdersEquity',
	'totalStockholdersEquity',
	'totalEquity',
	'minorityInterest',
	'totalLiabilitiesAndTotalEquity',
	'totalInvestments',
	'totalDebt',
	'netDebt',
] as const

const cashFlowStatement = [
	'netIncome',
	'depreciationAndAmortization',
	'deferredIncomeTax',
	'stockBasedCompensation',
	'changeInWorkingCapital',
	'accountsReceivables',
	'inventory',
	'accountsPayables',
	'otherWorkingCapital',
	'otherNonCashItems',
	'netCashProvidedByOperatingActivities',
	'investmentsInPropertyPlantAndEquipment',
	'acquisitionsNet',
	'purchasesOfInvestments',
	'salesMaturitiesOfInvestments',
	'otherInvestingActivities',
	'netCashProvidedByInvestingActivities',
	'netDebtIssuance',
	'longTermNetDebtIssuance',
	'shortTermNetDebtIssuance',
	'netStockIssuance',
	'netCommonStockIssuance',
	'commonStockIssuance',
	'commonStockRepurchased',
	'netPreferredStockIssuance',
	'netDividendsPaid',
	'commonDividendsPaid',
	'preferredDividendsPaid',
	'otherFinancingActivities',
	'netCashProvidedByFinancingActivities',
	'effectOfForexChangesOnCash',
	'netChangeInCash',
	'cashAtEndOfPeriod',
	'cashAtBeginningOfPeriod',
	'operatingCashFlow',
	'capitalExpenditure',
	'freeCashFlow',
	'incomeTaxesPaid',
	'interestPaid',
] as const

const keyMetrics = [
	'marketCap',
	'enterpriseValue',
	'evToSales',
	'evToOperatingCashFlow',
	'evToFreeCashFlow',
	'evToEBITDA',
	'netDebtToEBITDA',
	'currentRatio',
	'incomeQuality',
	'grahamNumber',
	'grahamNetNet',
	'taxBurden',
	'interestBurden',
	'workingCapital',
	'investedCapital',
	'returnOnAssets',
	'operatingReturnOnAssets',
	'returnOnTangibleAssets',
	'returnOnEquity',
	'returnOnInvestedCapital',
	'returnOnCapitalEmployed',
	'earningsYield',
	'freeCashFlowYield',
	'capexToOperatingCashFlow',
	'capexToDepreciation',
	'capexToRevenue',
	'salesGeneralAndAdministrativeToRevenue',
	'researchAndDevelopementToRevenue',
	'stockBasedCompensationToRevenue',
	'intangiblesToTotalAssets',
	'averageReceivables',
	'averagePayables',
	'averageInventory',
	'daysOfSalesOutstanding',
	'daysOfPayablesOutstanding',
	'daysOfInventoryOutstanding',
	'operatingCycle',
	'cashConversionCycle',
	'freeCashFlowToEquity',
	'freeCashFlowToFirm',
	'tangibleAssetValue',
	'netCurrentAssetValue',
] as const

const keyMetricsTtm = [
	'marketCapTTM',
	'enterpriseValueTTM',
	'evToSalesTTM',
	'evToOperatingCashFlowTTM',
	'evToFreeCashFlowTTM',
	'evToEBITDATTM',
	'netDebtToEBITDATTM',
	'currentRatioTTM',
	'incomeQualityTTM',
	'grahamNumberTTM',
	'grahamNetNetTTM',
	'taxBurdenTTM',
	'interestBurdenTTM',
	'workingCapitalTTM',
	'investedCapitalTTM',
	'returnOnAssetsTTM',
	'operatingReturnOnAssetsTTM',
	'returnOnTangibleAssetsTTM',
	'returnOnEquityTTM',
	'returnOnInvestedCapitalTTM',
	'returnOnCapitalEmployedTTM',
	'earningsYieldTTM',
	'freeCashFlowYieldTTM',
	'capexToOperatingCashFlowTTM',
	'capexToDepreciationTTM',
	'capexToRevenueTTM',
	'salesGeneralAndAdministrativeToRevenueTTM',
	'researchAndDevelopementToRevenueTTM',
	'stockBasedCompensationToRevenueTTM',
	'intangiblesToTotalAssetsTTM',
	'averageReceivablesTTM',
	'averagePayablesTTM',
	'averageInventoryTTM',
	'daysOfSalesOutstandingTTM',
	'daysOfPayablesOutstandingTTM',
	'daysOfInventoryOutstandingTTM',
	'operatingCycleTTM',
	'cashConversionCycleTTM',
	'freeCashFlowToEquityTTM',
	'freeCashFlowToFirmTTM',
	'tangibleAssetValueTTM',
	'netCurrentAssetValueTTM',
] as const

const financialRatios = [
	'grossProfitMargin',
	'ebitMargin',
	'ebitdaMargin',
	'operatingProfitMargin',
	'pretaxProfitMargin',
	'continuousOperationsProfitMargin',
	'netProfitMargin',
	'bottomLineProfitMargin',
	'receivablesTurnover',
	'payablesTurnover',
	'inventoryTurnover',
	'fixedAssetTurnover',
	'assetTurnover',
	'currentRatio',
	'quickRatio',
	'solvencyRatio',
	'cashRatio',
	'priceToEarningsRatio',
	'priceToEarningsGrowthRatio',
	'forwardPriceToEarningsGrowthRatio',
	'priceToBookRatio',
	'priceToSalesRatio',
	'priceToFreeCashFlowRatio',
	'priceToOperatingCashFlowRatio',
	'debtToAssetsRatio',
	'debtToEquityRatio',
	'debtToCapitalRatio',
	'longTermDebtToCapitalRatio',
	'financialLeverageRatio',
	'workingCapitalTurnoverRatio',
	'operatingCashFlowRatio',
	'operatingCashFlowSalesRatio',
	'freeCashFlowOperatingCashFlowRatio',
	'debtServiceCoverageRatio',
	'interestCoverageRatio',
	'shortTermOperatingCashFlowCoverageRatio',
	'operatingCashFlowCoverageRatio',
	'capitalExpenditureCoverageRatio',
	'dividendPaidAndCapexCoverageRatio',
	'dividendPayoutRatio',
	'dividendYield',
	'dividendYieldPercentage',
	'revenuePerShare',
	'netIncomePerShare',
	'interestDebtPerShare',
	'cashPerShare',
	'bookValuePerShare',
	'tangibleBookValuePerShare',
	'shareholdersEquityPerShare',
	'operatingCashFlowPerShare',
	'capexPerShare',
	'freeCashFlowPerShare',
	'netIncomePerEBT',
	'ebtPerEbit',
	'priceToFairValue',
	'debtToMarketCap',
	'effectiveTaxRate',
	'enterpriseValueMultiple',
] as const

const financialRatiosTtm = [
	'grossProfitMarginTTM',
	'ebitMarginTTM',
	'ebitdaMarginTTM',
	'operatingProfitMarginTTM',
	'pretaxProfitMarginTTM',
	'continuousOperationsProfitMarginTTM',
	'netProfitMarginTTM',
	'bottomLineProfitMarginTTM',
	'receivablesTurnoverTTM',
	'payablesTurnoverTTM',
	'inventoryTurnoverTTM',
	'fixedAssetTurnoverTTM',
	'assetTurnoverTTM',
	'currentRatioTTM',
	'quickRatioTTM',
	'solvencyRatioTTM',
	'cashRatioTTM',
	'priceToEarningsRatioTTM',
	'priceToEarningsGrowthRatioTTM',
	'forwardPriceToEarningsGrowthRatioTTM',
	'priceToBookRatioTTM',
	'priceToSalesRatioTTM',
	'priceToFreeCashFlowRatioTTM',
	'priceToOperatingCashFlowRatioTTM',
	'debtToAssetsRatioTTM',
	'debtToEquityRatioTTM',
	'debtToCapitalRatioTTM',
	'longTermDebtToCapitalRatioTTM',
	'financialLeverageRatioTTM',
	'workingCapitalTurnoverRatioTTM',
	'operatingCashFlowRatioTTM',
	'operatingCashFlowSalesRatioTTM',
	'freeCashFlowOperatingCashFlowRatioTTM',
	'debtServiceCoverageRatioTTM',
	'interestCoverageRatioTTM',
	'shortTermOperatingCashFlowCoverageRatioTTM',
	'operatingCashFlowCoverageRatioTTM',
	'capitalExpenditureCoverageRatioTTM',
	'dividendPaidAndCapexCoverageRatioTTM',
	'dividendPayoutRatioTTM',
	'dividendYieldTTM',
	'dividendYieldPercentageTTM',
	'enterpriseValueTTM',
	'revenuePerShareTTM',
	'netIncomePerShareTTM',
	'interestDebtPerShareTTM',
	'cashPerShareTTM',
	'bookValuePerShareTTM',
	'tangibleBookValuePerShareTTM',
	'shareholdersEquityPerShareTTM',
	'operatingCashFlowPerShareTTM',
	'capexPerShareTTM',
	'freeCashFlowPerShareTTM',
	'netIncomePerEBTTTM',
	'ebtPerEbitTTM',
	'priceToFairValueTTM',
	'debtToMarketCapTTM',
	'effectiveTaxRateTTM',
	'enterpriseValueMultipleTTM',
] as const

const financialScores = [
	'altmanZScore',
	'piotroskiScore',
	'workingCapital',
	'totalAssets',
	'retainedEarnings',
	'ebit',
	'marketCap',
	'totalLiabilities',
	'revenue',
] as const

const ownerEarnings = [
	'averagePPE',
	'maintenanceCapex',
	'ownersEarnings',
	'growthCapex',
	'ownersEarningsPerShare',
] as const

const enterpriseValues = [
	'numberOfShares',
	'marketCapitalization',
	'minusCashAndCashEquivalents',
	'addTotalDebt',
	'enterpriseValue',
] as const

const incomeStatementGrowth = [
	'growthRevenue',
	'growthCostOfRevenue',
	'growthGrossProfit',
	'growthGrossProfitRatio',
	'growthResearchAndDevelopmentExpenses',
	'growthGeneralAndAdministrativeExpenses',
	'growthSellingAndMarketingExpenses',
	'growthOtherExpenses',
	'growthOperatingExpenses',
	'growthCostAndExpenses',
	'growthInterestIncome',
	'growthInterestExpense',
	'growthDepreciationAndAmortization',
	'growthEBITDA',
	'growthOperatingIncome',
	'growthIncomeBeforeTax',
	'growthIncomeTaxExpense',
	'growthNetIncome',
	'growthEPS',
	'growthEPSDiluted',
	'growthWeightedAverageShsOut',
	'growthWeightedAverageShsOutDil',
	'growthEBIT',
	'growthNonOperatingIncomeExcludingInterest',
	'growthNetInterestIncome',
	'growthTotalOtherIncomeExpensesNet',
	'growthNetIncomeFromContinuingOperations',
	'growthOtherAdjustmentsToNetIncome',
	'growthNetIncomeDeductions',
] as const

const balanceSheetStatementGrowth = [
	'growthCashAndCashEquivalents',
	'growthShortTermInvestments',
	'growthCashAndShortTermInvestments',
	'growthNetReceivables',
	'growthInventory',
	'growthOtherCurrentAssets',
	'growthTotalCurrentAssets',
	'growthPropertyPlantEquipmentNet',
	'growthGoodwill',
	'growthIntangibleAssets',
	'growthGoodwillAndIntangibleAssets',
	'growthLongTermInvestments',
	'growthTaxAssets',
	'growthOtherNonCurrentAssets',
	'growthTotalNonCurrentAssets',
	'growthOtherAssets',
	'growthTotalAssets',
	'growthAccountPayables',
	'growthShortTermDebt',
	'growthTaxPayables',
	'growthDeferredRevenue',
	'growthOtherCurrentLiabilities',
	'growthTotalCurrentLiabilities',
	'growthLongTermDebt',
	'growthDeferredRevenueNonCurrent',
	'growthDeferredTaxLiabilitiesNonCurrent',
	'growthOtherNonCurrentLiabilities',
	'growthTotalNonCurrentLiabilities',
	'growthOtherLiabilities',
	'growthTotalLiabilities',
	'growthPreferredStock',
	'growthCommonStock',
	'growthRetainedEarnings',
	'growthAccumulatedOtherComprehensiveIncomeLoss',
	'growthOthertotalStockholdersEquity',
	'growthTotalStockholdersEquity',
	'growthMinorityInterest',
	'growthTotalEquity',
	'growthTotalLiabilitiesAndStockholdersEquity',
	'growthTotalInvestments',
	'growthTotalDebt',
	'growthNetDebt',
	'growthAccountsReceivables',
	'growthOtherReceivables',
	'growthPrepaids',
	'growthTotalPayables',
	'growthOtherPayables',
	'growthAccruedExpenses',
	'growthCapitalLeaseObligationsCurrent',
	'growthAdditionalPaidInCapital',
	'growthTreasuryStock',
] as const

const cashFlowStatementGrowth = [
	'growthNetIncome',
	'growthDepreciationAndAmortization',
	'growthDeferredIncomeTax',
	'growthStockBasedCompensation',
	'growthChangeInWorkingCapital',
	'growthAccountsReceivables',
	'growthInventory',
	'growthAccountsPayables',
	'growthOtherWorkingCapital',
	'growthOtherNonCashItems',
	'growthNetCashProvidedByOperatingActivites',
	'growthInvestmentsInPropertyPlantAndEquipment',
	'growthAcquisitionsNet',
	'growthPurchasesOfInvestments',
	'growthSalesMaturitiesOfInvestments',
	'growthOtherInvestingActivites',
	'growthNetCashUsedForInvestingActivites',
	'growthDebtRepayment',
	'growthCommonStockIssued',
	'growthCommonStockRepurchased',
	'growthDividendsPaid',
	'growthOtherFinancingActivites',
	'growthNetCashUsedProvidedByFinancingActivities',
	'growthEffectOfForexChangesOnCash',
	'growthNetChangeInCash',
	'growthCashAtEndOfPeriod',
	'growthCashAtBeginningOfPeriod',
	'growthOperatingCashFlow',
	'growthCapitalExpenditure',
	'growthFreeCashFlow',
	'growthNetDebtIssuance',
	'growthLongTermNetDebtIssuance',
	'growthShortTermNetDebtIssuance',
	'growthNetStockIssuance',
	'growthPreferredDividendsPaid',
	'growthIncomeTaxesPaid',
	'growthInterestPaid',
] as const

const financialStatementGrowth = [
	'revenueGrowth',
	'grossProfitGrowth',
	'ebitgrowth',
	'operatingIncomeGrowth',
	'netIncomeGrowth',
	'epsgrowth',
	'epsdilutedGrowth',
	'weightedAverageSharesGrowth',
	'weightedAverageSharesDilutedGrowth',
	'dividendsPerShareGrowth',
	'operatingCashFlowGrowth',
	'receivablesGrowth',
	'inventoryGrowth',
	'assetGrowth',
	'bookValueperShareGrowth',
	'debtGrowth',
	'rdexpenseGrowth',
	'sgaexpensesGrowth',
	'freeCashFlowGrowth',
	'tenYRevenueGrowthPerShare',
	'fiveYRevenueGrowthPerShare',
	'threeYRevenueGrowthPerShare',
	'tenYOperatingCFGrowthPerShare',
	'fiveYOperatingCFGrowthPerShare',
	'threeYOperatingCFGrowthPerShare',
	'tenYNetIncomeGrowthPerShare',
	'fiveYNetIncomeGrowthPerShare',
	'threeYNetIncomeGrowthPerShare',
	'tenYShareholdersEquityGrowthPerShare',
	'fiveYShareholdersEquityGrowthPerShare',
	'threeYShareholdersEquityGrowthPerShare',
	'tenYDividendperShareGrowthPerShare',
	'fiveYDividendperShareGrowthPerShare',
	'threeYDividendperShareGrowthPerShare',
	'ebitdaGrowth',
	'growthCapitalExpenditure',
	'tenYBottomLineNetIncomeGrowthPerShare',
	'fiveYBottomLineNetIncomeGrowthPerShare',
	'threeYBottomLineNetIncomeGrowthPerShare',
] as const

const financialEstimates = [
	'revenueLow',
	'revenueHigh',
	'revenueAvg',
	'ebitdaLow',
	'ebitdaHigh',
	'ebitdaAvg',
	'ebitLow',
	'ebitHigh',
	'ebitAvg',
	'netIncomeLow',
	'netIncomeHigh',
	'netIncomeAvg',
	'sgaExpenseLow',
	'sgaExpenseHigh',
	'sgaExpenseAvg',
	'epsAvg',
	'epsHigh',
	'epsLow',
	'numAnalystsRevenue',
	'numAnalystsEps',
] as const

const dcfValuation = ['dcf'] as const

const dcfAnalysis = [
	'revenue',
	'revenuePercentage',
	'ebitda',
	'ebitdaPercentage',
	'ebit',
	'ebitPercentage',
	'depreciation',
	'depreciationPercentage',
	'totalCash',
	'totalCashPercentage',
	'receivables',
	'receivablesPercentage',
	'inventories',
	'inventoriesPercentage',
	'payable',
	'payablePercentage',
	'capitalExpenditure',
	'capitalExpenditurePercentage',
	'price',
	'beta',
	'dilutedSharesOutstanding',
	'costofDebt',
	'taxRate',
	'afterTaxCostOfDebt',
	'riskFreeRate',
	'marketRiskPremium',
	'costOfEquity',
	'totalDebt',
	'totalEquity',
	'totalCapital',
	'debtWeighting',
	'equityWeighting',
	'wacc',
	'taxRateCash',
	'ebiat',
	'ufcf',
	'sumPvUfcf',
	'longTermGrowthRate',
	'terminalValue',
	'presentTerminalValue',
	'enterpriseValue',
	'netDebt',
	'equityValue',
	'equityValuePerShare',
	'freeCashFlowT1',
] as const

const priceTargetSummary = [
	'lastMonthCount',
	'lastMonthAvgPriceTarget',
	'lastQuarterCount',
	'lastQuarterAvgPriceTarget',
	'lastYearCount',
	'lastYearAvgPriceTarget',
	'allTimeCount',
	'allTimeAvgPriceTarget',
	'publishers',
] as const

const priceTargetConsensus = ['targetHigh', 'targetLow', 'targetConsensus', 'targetMedian'] as const

const priceTargetNews = [
	'publishedDate',
	'newsURL',
	'newsTitle',
	'analystName',
	'priceTarget',
	'adjPriceTarget',
	'priceWhenPosted',
	'newsPublisher',
	'newsBaseURL',
	'analystCompany',
] as const

const stockGrades = ['gradingCompany', 'previousGrade', 'newGrade', 'action'] as const

const stockGradeConsensus = ['strongBuy', 'buy', 'hold', 'sell', 'strongSell', 'consensus'] as const

const stockGradeNews = [
	'publishedDate',
	'newsURL',
	'newsTitle',
	'newsBaseURL',
	'newsPublisher',
	'newGrade',
	'previousGrade',
	'gradingCompany',
	'action',
	'priceWhenPosted',
] as const

const simpleMovingAverage = ['sma']

const exponentialMovingAverage = ['ema']

const weightedMovingAverage = ['wma']

const doubleExponentialMovingAverage = ['dema']

const tripleExponentialMovingAverage = ['tema']

const relativeStrengthIndex = ['rsi']

const standardDeviation = ['standardDeviation']

const williamsPercentR = ['williams']

const averageDirectionalIndex = ['adx']

const economicIndicators = [
	'GDP',
	'realGDP',
	'nominalPotentialGDP',
	'realGDPPerCapita',
	'federalFunds',
	'CPI',
	'inflationRate',
	'inflation',
	'retailSales',
	'consumerSentiment',
	'durableGoods',
	'unemploymentRate',
	'totalNonfarmPayroll',
	'initialClaims',
	'industrialProductionTotalIndex',
	'newPrivatelyOwnedHousingUnitsStartedTotalUnits',
	'totalVehicleSales',
	'retailMoneyFunds',
	'smoothedUSRecessionProbabilities',
	'3MonthOr90DayRatesAndYieldsCertificatesOfDeposit',
	'commercialBankInterestRateOnCreditCardPlansAllAccounts',
	'30YearFixedRateMortgageAverage',
	'15YearFixedRateMortgageAverage',
] as const

type ApiFunctionNames = {
	[K in keyof typeof api]: (typeof api)[K] extends (...args: any[]) => any ? K : never
}[keyof typeof api]

export const returns: Partial<Record<ApiFunctionNames, readonly string[]>> = {
	companyProfile,
	incomeStatement,
	balanceSheetStatement,
	cashFlowStatement,
	keyMetrics,
	keyMetricsTtm,
	financialRatios,
	financialRatiosTtm,
	financialScores,
	ownerEarnings,
	enterpriseValues,
	incomeStatementGrowth,
	balanceSheetStatementGrowth,
	cashFlowStatementGrowth,
	financialStatementGrowth,
	financialEstimates,
	dcfValuation,
	dcfAnalysis,
	priceTargetSummary,
	priceTargetConsensus,
	priceTargetNews,
	stockGrades,
	stockGradeConsensus,
	stockGradeNews,
	simpleMovingAverage,
	exponentialMovingAverage,
	weightedMovingAverage,
	doubleExponentialMovingAverage,
	tripleExponentialMovingAverage,
	relativeStrengthIndex,
	standardDeviation,
	williamsPercentR,
	averageDirectionalIndex,
	economicIndicators,
}
