export const INCLUDED_API_FUNCTIONS: Set<string> = new Set([
	// SEARCH
	'searchSymbol', // Searches for financial instruments by symbol. (query; options (limit, exchange)) -> symbol, name, currency, exchangeFullName, exchange
	'searchName', // Searches for financial instruments by company name. (query; options (limit, exchange)) -> symbol, name, currency, exchangeFullName, exchange
	// 'searchCik', // Searches for companies by CIK (Central Index Key). (cik; options (limit)) -> symbol, companyName, cik, exchangeFullName, exchange, currency
	// 'searchCusip', // Searches for financial instruments by CUSIP. (cusip) -> symbol, companyName, cusip, marketCap
	// 'searchIsin', // Searches for financial instruments by ISIN. (isin) -> symbol, name, isin, marketCap
	// 'stockScreener', // Screens for companies based on a wide range of financial and market criteria. (params (marketCapMoreThan, marketCapLowerThan, priceMoreThan, priceLowerThan, betaMoreThan, betaLowerThan, volumeMoreThan, volumeLowerThan, dividendMoreThan, dividendLowerThan, isEtf, isFund, isActivelyTrading, sector, industry, country, exchange, limit, includeAllShareClasses)) -> symbol, companyName, marketCap, sector, industry, beta, price, lastAnnualDividend, volume, exchange, exchangeShortName, country, isEtf, isFund, isActivelyTrading
	// 'searchExchangeVariants', // Searches for different exchange listings (variants) of a given stock symbol. (symbol) -> symbol, price, beta, volAvg, mktCap, lastDiv, range, changes, companyName, currency, cik, isin, cusip, exchange, exchangeShortName, industry, website, description, ceo, sector, country, fullTimeEmployees, phone, address, city, state, zip, dcfDiff, dcf, image, ipoDate, defaultImage, isEtf, isActivelyTrading, isAdr, isFund

	// DIRECTORY
	// 'listCompanySymbols', // Retrieves a comprehensive list of company symbols. (No parameters.) -> symbol, companyName
	// 'listFinancialStatementSymbols', // Retrieves a list of symbols for companies that have financial statements available. (No parameters.) -> symbol, companyName, tradingCurrency, reportingCurrency
	// 'listCik', // Retrieves a list of CIKs (Central Index Keys). (options (limit)) -> cik, companyName
	// 'listSymbolChanges', // Retrieves a list of stock symbol changes. (options (invalid, limit)) -> date, companyName, oldSymbol, newSymbol
	// 'listEtfSymbol', // Retrieves a list of ETF symbols. (No parameters.) -> symbol, name
	// 'listActivelyTrading', // Retrieves a list of actively trading companies and financial instruments. (No parameters.) -> symbol, name
	// 'availableExchanges', // Retrieves a list of available stock exchanges. (No parameters.) -> exchange
	// 'availableSectors', // Retrieves a list of available industry sectors. (No parameters.) -> sector
	// 'availableIndustries', // Retrieves a list of available industries. (No parameters.) -> industry
	// 'availableCountries', // Retrieves a list of available countries where stock symbols are available. (No parameters.) -> country

	// ANALYST
	'financialEstimates', // Retrieves analyst financial estimates for a given stock symbol. (symbol; options (period, page, limit)) -> symbol, date, revenueLow, revenueHigh, revenueAvg, ebitdaLow, ebitdaHigh, ebitdaAvg, ebitLow, ebitHigh, ebitAvg, netIncomeLow, netIncomeHigh, netIncomeAvg, sgaExpenseLow, sgaExpenseHigh, sgaExpenseAvg, epsAvg, epsHigh, epsLow, numAnalystsRevenue, numAnalystsEps
	// 'ratingsSnapshot', // Retrieves a snapshot of financial ratings for a given stock symbol. (symbol; options (limit)) -> symbol, rating, overallScore, discountedCashFlowScore, returnOnEquityScore, returnOnAssetsScore, debtToEquityScore, priceToEarningsScore, priceToBookScore
	// 'historicalRatings', // Retrieves historical financial ratings for a given stock symbol. (symbol; options (limit)) -> date, symbol, rating, overallScore, discountedCashFlowScore, returnOnEquityScore, returnOnAssetsScore, debtToEquityScore, priceToEarningsScore, priceToBookScore
	'priceTargetSummary', // Retrieves a summary of analyst price targets for a given stock symbol. (symbol) -> symbol, lastMonthCount, lastMonthAvgPriceTarget, lastQuarterCount, lastQuarterAvgPriceTarget, lastYearCount, lastYearAvgPriceTarget, allTimeCount, allTimeAvgPriceTarget, publishers
	'priceTargetConsensus', // Retrieves the consensus price targets (high, low, consensus, median) for a given stock symbol. (symbol) -> symbol, targetHigh, targetLow, targetConsensus, targetMedian
	'priceTargetNews', // Retrieves news articles related to analyst price target changes for a given stock symbol. (symbol; options (page, limit)) -> symbol, publishedDate, newsURL, newsTitle, analystName, priceTarget, adjPriceTarget, priceWhenPosted, newsPublisher, newsBaseURL, analystCompany
	// 'latestPriceTargetNews', // Retrieves the latest price target news across all stock symbols. (options (page, limit)) -> symbol, publishedDate, newsURL, newsTitle, analystName, priceTarget, adjPriceTarget, priceWhenPosted, newsPublisher, newsBaseURL, analystCompany
	// 'historicalStockGrades', // Retrieves historical stock grades for a given stock symbol. This endpoint returns a summary of buy/hold/sell counts per date. (symbol; options (limit)) -> symbol, date, analystRatingsBuy, analystRatingsHold, analystRatingsSell, analystRatingsStrongSell
	'stockGrades', // Retrieves current stock grades (e.g., buy, sell, hold) from analysts for a given stock symbol. (symbol) -> symbol, date, gradingCompany, previousGrade, newGrade, action
	'stockGradeConsensus', // Retrieves a summary of analyst stock grade consensus (strong buy, buy, hold, sell, strong sell) for a given stock symbol. (symbol) -> symbol, strongBuy, buy, hold, sell, strongSell, consensus
	'stockGradeNews', // Retrieves news articles related to analyst stock grade changes for a given stock symbol. (symbol; options (page, limit)) -> symbol, publishedDate, newsURL, newsTitle, newsBaseURL, newsPublisher, newGrade, previousGrade, gradingCompany, action, priceWhenPosted
	// 'latestStockGradeNews', // Retrieves the latest stock grade news across all stock symbols. (options (page, limit)) -> symbol, publishedDate, newsURL, newsTitle, newsBaseURL, newsPublisher, newGrade, previousGrade, gradingCompany, action, priceWhenPosted

	// CALENDAR
	'companyDividends', // Retrieves dividend history for a specific company. (symbol; options (limit)) -> symbol, date, recordDate, paymentDate, declarationDate, adjDividend, dividend, yield, frequency
	// 'dividendsCalendar', // Retrieves a calendar of dividend events for all stocks within a date range. (options (from, to)) -> symbol, date, recordDate, paymentDate, declarationDate, adjDividend, dividend, yield, frequency
	'companyEarningsReports', // Retrieves earnings report history for a specific company. (symbol; options (limit)) -> symbol, date, epsActual, epsEstimated, revenueActual, revenueEstimated, lastUpdated
	// 'earningsCalendar', // Retrieves a calendar of earnings announcements for all stocks within a date range. (options (from, to)) -> symbol, date, epsActual, epsEstimated, revenueActual, revenueEstimated, lastUpdated
	// 'iposCalendar', // Retrieves a calendar of upcoming Initial Public Offerings (IPOs). (options (from, to)) -> symbol, date, daa, company, exchange, actions, shares, priceRange, marketCap
	// 'ipoDisclosures', // Retrieves a list of disclosure filings for upcoming IPOs. (options (from, to)) -> symbol, filingDate, acceptedDate, effectivenessDate, cik, form, url
	// 'ipoProspectus', // Retrieves information on IPO prospectuses. (options (from, to)) -> symbol, acceptedDate, filingDate, ipoDate, cik, pricePublicPerShare, pricePublicTotal, discountsAndCommissionsPerShare, discountsAndCommissionsTotal, proceedsBeforeExpensesPerShare, proceedsBeforeExpensesTotal, form, url
	// 'stockSplitDetails', // Retrieves stock split details for a specific company. (symbol; options (limit)) -> symbol, date, numerator, denominator
	// 'stockSplitsCalendar', // Retrieves a calendar of upcoming stock splits. (options (from, to)) -> symbol, date, numerator, denominator

	// CHART
	// 'stockChartLight', // Retrieves simplified historical end-of-day stock chart data (date, price, volume). (symbol; options (from, to)) -> symbol, date, price, volume
	'stockChartFull', // Retrieves full historical end-of-day stock price and volume data. (symbol; options (from, to)) -> symbol, change, changePercent, vwap, date, open, high, low, close, volume
	// 'unadjustedStockChart', // Retrieves unadjusted historical end-of-day stock price data. (symbol; options (from, to)) -> symbol, date, adjOpen, adjHigh, adjLow, adjClose, volume
	// 'dividendAdjustedStockChart', // Retrieves dividend-adjusted historical end-of-day stock price data. (symbol; options (from, to)) -> symbol, date, adjOpen, adjHigh, adjLow, adjClose, volume
	// 'historicalIntradayChart', // Retrieves historical intraday stock chart data for a specific timeframe. (symbol; timeframe; options (from, to)) -> date, open, high, low, close, volume
	// 'stockChart1Min', // Retrieves 1-minute interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'stockChart5Min', // Retrieves 5-minute interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'stockChart15Min', // Retrieves 15-minute interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'stockChart30Min', // Retrieves 30-minute interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'stockChart1Hour', // Retrieves 1-hour interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'stockChart4Hour', // Retrieves 4-hour interval historical stock chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume

	// COMPANY
	'companyProfile', // Retrieves detailed company profile data for a given stock symbol. (symbol) -> symbol, price, marketCap, beta, lastDividend, range, change, changePercentage, volume, averageVolume, companyName, currency, cik, isin, cusip, exchangeFullName, exchange, industry, website, description, ceo, sector, country, fullTimeEmployees, phone, address, city, state, zip, image, ipoDate, defaultImage, isEtf, isActivelyTrading, isAdr, isFund
	// 'companyProfileByCik', // Retrieves detailed company profile data by CIK. (cik) -> symbol, price, marketCap, beta, lastDividend, range, change, changePercentage, volume, averageVolume, companyName, currency, cik, isin, cusip, exchangeFullName, exchange, industry, website, description, ceo, sector, country, fullTimeEmployees, phone, address, city, state, zip, image, ipoDate, defaultImage, isEtf, isActivelyTrading, isAdr, isFund
	// 'companyNotes', // Retrieves information about company-issued notes for a given stock symbol. (symbol) -> cik, symbol, title, exchange
	'stockPeers', // Retrieves a list of peer companies for a given stock symbol. (symbol) -> symbol, companyName, price, mktCap
	// 'delistedCompanies', // Retrieves a list of delisted companies. (options (page, limit)) -> symbol, companyName, exchange, ipoDate, delistedDate
	'companyEmployeeCount', // Retrieves employee count information for a given company. (symbol; options (limit)) -> symbol, cik, acceptanceTime, periodOfReport, companyName, formType, filingDate, employeeCount, source
	'historicalCompanyEmployeeCount', // Retrieves historical employee count data for a given company. (symbol; options (limit)) -> symbol, cik, acceptanceTime, periodOfReport, companyName, formType, filingDate, employeeCount, source
	'companyMarketCap', // Retrieves the market capitalization for a specific company on the current date. (symbol) -> symbol, date, marketCap
	// 'batchMarketCap', // Retrieves market capitalization data for multiple companies in a single request. (symbols) -> symbol, date, marketCap
	'historicalMarketCap', // Retrieves historical market capitalization data for a company. (symbol; options (limit, from, to)) -> symbol, date, marketCap
	'companySharesFloat', // Retrieves share float and liquidity data for a company. (symbol) -> symbol, date, freeFloat, floatShares, outstandingShares
	// 'allSharesFloat', // Retrieves shares float data for all available companies. (options (limit, page)) -> symbol, date, freeFloat, floatShares, outstandingShares
	// 'latestMergersAcquisitions', // Retrieves the latest mergers and acquisitions data. (options (page, limit)) -> symbol, companyName, cik, targetedCompanyName, targetedCik, targetedSymbol, transactionDate, acceptedDate, link
	'searchMergersAcquisitions', // Searches for mergers and acquisitions data by name. (name) -> symbol, companyName, cik, targetedCompanyName, targetedCik, targetedSymbol, transactionDate, acceptedDate, link
	'companyExecutives', // Retrieves information on company executives for a given stock symbol. (symbol; options (active)) -> title, name, pay, currencyPay, gender, yearBorn, active
	'executiveCompensation', // Retrieves executive compensation data for a given stock symbol. (symbol) -> cik, symbol, companyName, filingDate, acceptedDate, nameAndPosition, year, salary, bonus, stockAward, optionAward, incentivePlanCompensation, allOtherCompensation, total, link
	'executiveCompensationBenchmark', // Retrieves average executive compensation data across various industries for a specific year. (year) -> industryTitle, year, averageCompensation

	// COMMITMENT OF TRADERS (COT)
	'cotReport', // Retrieves Commitment of Traders (COT) reports. (options (symbol, from, to)) -> symbol, date, name, sector, marketAndExchangeNames, cftcContractMarketCode, cftcMarketCode, cftcRegionCode, cftcCommodityCode, openInterestAll, noncommPositionsLongAll, noncommPositionsShortAll, noncommPositionsSpreadAll, commPositionsLongAll, commPositionsShortAll, totReptPositionsLongAll, totReptPositionsShortAll, nonreptPositionsLongAll, nonreptPositionsShortAll, openInterestOld, noncommPositionsLongOld, noncommPositionsShortOld, noncommPositionsSpreadOld, commPositionsLongOld, commPositionsShortOld, totReptPositionsLongOld, totReptPositionsShortOld, nonreptPositionsLongOld, nonreptPositionsShortOld, openInterestOther, noncommPositionsLongOther, noncommPositionsShortOther, noncommPositionsSpreadOther, commPositionsLongOther, commPositionsShortOther, totReptPositionsLongOther, totReptPositionsShortOther, nonreptPositionsLongOther, nonreptPositionsShortOther, changeInOpenInterestAll, changeInNoncommLongAll, changeInNoncommShortAll, changeInNoncommSpeadAll, changeInCommLongAll, changeInCommShortAll, changeInTotReptLongAll, changeInTotReptShortAll, changeInNonreptLongAll, changeInNonreptShortAll, pctOfOpenInterestAll, pctOfOiNoncommLongAll, pctOfOiNoncommShortAll, pctOfOiNoncommSpreadAll, pctOfOiCommLongAll, pctOfOiCommShortAll, pctOfOiTotReptLongAll, pctOfOiTotReptShortAll, pctOfOiNonreptLongAll, pctOfOiNonreptShortAll, pctOfOpenInterestOl, pctOfOiNoncommLongOl, pctOfOiNoncommShortOl, pctOfOiNoncommSpreadOl, pctOfOiCommLongOl, and 64 more. Refer to tool schema for full list.
	'cotAnalysis', // Retrieves analysis of Commitment of Traders (COT) reports for a specific date range. (options (symbol, from, to)) -> symbol, date, name, sector, exchange, currentLongMarketSituation, currentShortMarketSituation, marketSituation, previousLongMarketSituation, previousShortMarketSituation, previousMarketSituation, netPosition, previousNetPosition, changeInNetPosition, marketSentiment, reversalTrend
	'cotReportList', // Retrieves a list of available Commitment of Traders (COT) report symbols. (No parameters.) -> symbol, name

	// DISCOUNTED CASH FLOW (DCF)
	'dcfValuation', // Retrieves a Discounted Cash Flow (DCF) valuation for a company. (symbol) -> symbol, date, dcf, Stock Price
	'leveredDcfValuation', // Retrieves a Levered Discounted Cash Flow (DCF) valuation for a company. (symbol) -> symbol, date, dcf, Stock Price
	'dcfAnalysis', // Runs a custom (unlevered) Discounted Cash Flow (DCF) analysis. (symbol; params (revenueGrowthPct, ebitdaPct, depreciationAndAmortizationPct, cashAndShortTermInvestmentsPct, receivablesPct, inventoriesPct, payablePct, ebitPct, capitalExpenditurePct, operatingCashFlowPct, sellingGeneralAndAdministrativeExpensesPct, taxRate, longTermGrowthRate, costOfDebt, costOfEquity, marketRiskPremium, beta, riskFreeRate)) -> year, symbol, revenue, revenuePercentage, ebitda, ebitdaPercentage, ebit, ebitPercentage, depreciation, depreciationPercentage, totalCash, totalCashPercentage, receivables, receivablesPercentage, inventories, inventoriesPercentage, payable, payablePercentage, capitalExpenditure, capitalExpenditurePercentage, price, beta, dilutedSharesOutstanding, costofDebt, taxRate, afterTaxCostOfDebt, riskFreeRate, marketRiskPremium, costOfEquity, totalDebt, totalEquity, totalCapital, debtWeighting, equityWeighting, wacc, taxRateCash, ebiat, ufcf, sumPvUfcf, longTermGrowthRate, terminalValue, presentTerminalValue, enterpriseValue, netDebt, equityValue, equityValuePerShare, freeCashFlowT1
	'dcfLeveredAnalysis', // Runs a custom Levered Discounted Cash Flow (DCF) analysis. (symbol; params (revenueGrowthPct, ebitdaPct, depreciationAndAmortizationPct, cashAndShortTermInvestmentsPct, receivablesPct, inventoriesPct, payablePct, ebitPct, capitalExpenditurePct, operatingCashFlowPct, sellingGeneralAndAdministrativeExpensesPct, taxRate, longTermGrowthRate, costOfDebt, costOfEquity, marketRiskPremium, beta, riskFreeRate)) -> year, symbol, revenue, revenuePercentage, capitalExpenditure, capitalExpenditurePercentage, price, beta, dilutedSharesOutstanding, costofDebt, taxRate, afterTaxCostOfDebt, riskFreeRate, marketRiskPremium, costOfEquity, totalDebt, totalEquity, totalCapital, debtWeighting, equityWeighting, wacc, operatingCashFlow, operatingCashFlowPercentage, pvLfcf, sumPvLfcf, longTermGrowthRate, freeCashFlow, terminalValue, presentTerminalValue, enterpriseValue, netDebt, equityValue, equityValuePerShare, freeCashFlowT1

	// ECONOMICS
	'treasuryRates', // Retrieves Treasury rates for various maturities within a date range. (options (from, to)) -> date, month1, month2, month3, month6, year1, year2, year3, year5, year7, year10, year20, year30
	'economicIndicators', // Retrieves data for a specific economic indicator. (name enum (GDP, realGDP, nominalPotentialGDP, realGDPPerCapita, federalFunds, CPI, inflationRate, inflation, retailSales, consumerSentiment, durableGoods, unemploymentRate, totalNonfarmPayroll, initialClaims, industrialProductionTotalIndex, newPrivatelyOwnedHousingUnitsStartedTotalUnits, totalVehicleSales, retailMoneyFunds, smoothedUSRecessionProbabilities, 3MonthOr90DayRatesAndYieldsCertificatesOfDeposit, commercialBankInterestRateOnCreditCardPlansAllAccounts, 30YearFixedRateMortgageAverage, 15YearFixedRateMortgageAverage); options (from, to)) -> name, date, value
	'economicCalendar', // Retrieves a calendar of upcoming economic data releases. (options (from, to)) -> date, country, event, currency, previous, estimate, actual, change, impact, changePercentage
	// 'marketRiskPremium', // Retrieves market risk premium data. (No parameters.) -> country, continent, countryRiskPremium, totalEquityRiskPremium

	// ESG
	// 'esgDisclosures', // Retrieves ESG (Environmental, Social, Governance) disclosure data for a company. (symbol) -> date, acceptedDate, symbol, cik, companyName, formType, environmentalScore, socialScore, governanceScore, ESGScore, url
	// 'esgRatings', // Retrieves ESG ratings for a company. (symbol) -> symbol, cik, companyName, industry, fiscalYear, ESGRiskRating, industryRank
	// 'esgBenchmark', // Retrieves ESG benchmark comparison data for a specific year. (year) -> fiscalYear, sector, environmentalScore, socialScore, governanceScore, ESGScore

	// ETF AND MUTUAL FUND
	'etfFundHoldings', // Retrieves the holdings of an ETF or mutual fund. (symbol) -> symbol, asset, name, isin, securityCusip, sharesNumber, weightPercentage, marketValue, updatedAt, updated
	'etfFundInfo', // Retrieves information about an ETF or mutual fund. (symbol) -> symbol, name, description, isin, assetClass, securityCusip, domicile, website, etfCompany, expenseRatio, assetsUnderManagement, avgVolume, inceptionDate, nav, navCurrency, holdingsCount, updatedAt, sectorsList
	'etfFundCountryAllocation', // Retrieves the country allocation/weightings for an ETF or mutual fund. (symbol) -> country, weightPercentage
	// 'etfAssetExposure', // Retrieves which ETFs hold a specific stock asset. (symbol) -> symbol, asset, sharesNumber, weightPercentage, marketValue
	// 'etfSectorWeighting', // Retrieves the sector weightings for an ETF. (symbol) -> symbol, sector, weightPercentage
	'mutualFundEtfLatestDisclosures', // Retrieves the latest disclosures from mutual funds and ETFs for a specific holding. (symbol) -> cik, holder, shares, dateReported, change, weightPercent
	'mutualFundDisclosures', // Retrieves comprehensive disclosure data for a mutual fund. (symbol; options (year, quarter, cik)) -> cik, date, acceptedDate, symbol, name, lei, title, cusip, isin, balance, units, cur_cd, valUsd, pctVal, payoffProfile, assetCat, issuerCat, invCountry, isRestrictedSec, fairValLevel, isCashCollateral, isNonCashCollateral, isLoanByFund
	'searchMutualFundEtfDisclosuresByName', // Searches for mutual fund and ETF disclosures by name. (name) -> symbol, cik, classId, seriesId, entityName, entityOrgType, seriesName, className, reportingFileNumber, address, city, zipCode, state
	'fundEtfDisclosuresByDate', // Retrieves disclosure dates for mutual funds and ETFs. (symbol; options (cik)) -> date, year, quarter

	// COMMODITY
	// 'commoditiesList', // Retrieves a list of tracked commodities. (No parameters.) -> symbol, name, exchange, tradeMonth, currency
	'commodityQuote', // Retrieves a real-time price quote for a commodity. (symbol) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	// 'commodityQuoteShort', // Retrieves a short real-time price quote for a commodity. (symbol) -> symbol, price, change, volume
	// 'allCommoditiesQuotes', // Retrieves real-time quotes for multiple commodities. (options (short)) -> No specific return fields selectable, returns full object/array.
	// 'commodityChartLight', // Retrieves light historical end-of-day price data for a commodity. (symbol; options (from, to)) -> symbol, date, price, volume
	'commodityChartFull', // Retrieves full historical end-of-day price data for a commodity. (symbol; options (from, to)) -> symbol, change, changePercent, vwap, date, open, high, low, close, volume
	// 'commodityChart1Min', // Retrieves 1-minute interval historical commodity chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'commodityChart5Min', // Retrieves 5-minute interval historical commodity chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume
	// 'commodityChart1Hour', // Retrieves 1-hour interval historical commodity chart data. (symbol; options (from, to, nonadjusted)) -> date, open, high, low, close, volume

	// CROWDFUNDING
	// 'latestCrowdfundingCampaigns', // Retrieves the latest crowdfunding campaigns. (options (page, limit)) -> cik, companyName, date, filingDate, acceptedDate, formType, formSignification, nameOfIssuer, legalStatusForm, jurisdictionOrganization, issuerStreet, issuerCity, issuerStateOrCountry, issuerZipCode, issuerWebsite, intermediaryCompanyName, intermediaryCommissionCik, intermediaryCommissionFileNumber, compensationAmount, financialInterest, securityOfferedType, securityOfferedOtherDescription, numberOfSecurityOffered, offeringPrice, offeringAmount, overSubscriptionAccepted, overSubscriptionAllocationType, maximumOfferingAmount, offeringDeadlineDate, currentNumberOfEmployees, totalAssetMostRecentFiscalYear, totalAssetPriorFiscalYear, cashAndCashEquiValentMostRecentFiscalYear, cashAndCashEquiValentPriorFiscalYear, accountsReceivableMostRecentFiscalYear, accountsReceivablePriorFiscalYear, shortTermDebtMostRecentFiscalYear, shortTermDebtPriorFiscalYear, longTermDebtMostRecentFiscalYear, longTermDebtPriorFiscalYear, revenueMostRecentFiscalYear, revenuePriorFiscalYear, costGoodsSoldMostRecentFiscalYear, costGoodsSoldPriorFiscalYear, taxesPaidMostRecentFiscalYear, taxesPaidPriorFiscalYear, netIncomeMostRecentFiscalYear, netIncomePriorFiscalYear
	// 'searchCrowdfundingCampaigns', // Searches for crowdfunding campaigns by name. (name) -> cik, name, date
	// 'crowdfundingCampaignsByCik', // Retrieves crowdfunding campaigns by CIK. (cik) -> cik, companyName, date, filingDate, acceptedDate, formType, formSignification, nameOfIssuer, legalStatusForm, jurisdictionOrganization, issuerStreet, issuerCity, issuerStateOrCountry, issuerZipCode, issuerWebsite, intermediaryCompanyName, intermediaryCommissionCik, intermediaryCommissionFileNumber, compensationAmount, financialInterest, securityOfferedType, securityOfferedOtherDescription, numberOfSecurityOffered, offeringPrice, offeringAmount, overSubscriptionAccepted, overSubscriptionAllocationType, maximumOfferingAmount, offeringDeadlineDate, currentNumberOfEmployees, totalAssetMostRecentFiscalYear, totalAssetPriorFiscalYear, cashAndCashEquiValentMostRecentFiscalYear, cashAndCashEquiValentPriorFiscalYear, accountsReceivableMostRecentFiscalYear, accountsReceivablePriorFiscalYear, shortTermDebtMostRecentFiscalYear, shortTermDebtPriorFiscalYear, longTermDebtMostRecentFiscalYear, longTermDebtPriorFiscalYear, revenueMostRecentFiscalYear, revenuePriorFiscalYear, costGoodsSoldMostRecentFiscalYear, costGoodsSoldPriorFiscalYear, taxesPaidMostRecentFiscalYear, taxesPaidPriorFiscalYear, netIncomeMostRecentFiscalYear, netIncomePriorFiscalYear
	// 'latestEquityOfferingUpdates', // Retrieves the latest equity offering updates. (options (page, limit, cik)) -> cik, companyName, date, filingDate, acceptedDate, formType, formSignification, entityName, issuerStreet, issuerCity, issuerStateOrCountry, issuerStateOrCountryDescription, issuerZipCode, issuerPhoneNumber, jurisdictionOfIncorporation, entityType, incorporatedWithinFiveYears, yearOfIncorporation, relatedPersonFirstName, relatedPersonLastName, relatedPersonStreet, relatedPersonCity, relatedPersonStateOrCountry, relatedPersonStateOrCountryDescription, relatedPersonZipCode, relatedPersonRelationship, industryGroupType, revenueRange, federalExemptionsExclusions, isAmendment, dateOfFirstSale, durationOfOfferingIsMoreThanYear, securitiesOfferedAreOfEquityType, isBusinessCombinationTransaction, minimumInvestmentAccepted, totalOfferingAmount, totalAmountSold, totalAmountRemaining, hasNonAccreditedInvestors, totalNumberAlreadyInvested, salesCommissions, findersFees, grossProceedsUsed
	// 'searchEquityOfferings', // Searches for equity offerings by name. (name) -> cik, name, date
	// 'equityOfferingsByCik', // Retrieves equity offerings by CIK. (cik) -> cik, companyName, date, filingDate, acceptedDate, formType, formSignification, entityName, issuerStreet, issuerCity, issuerStateOrCountry, issuerStateOrCountryDescription, issuerZipCode, issuerPhoneNumber, jurisdictionOfIncorporation, entityType, incorporatedWithinFiveYears, yearOfIncorporation, relatedPersonFirstName, relatedPersonLastName, relatedPersonStreet, relatedPersonCity, relatedPersonStateOrCountry, relatedPersonStateOrCountryDescription, relatedPersonZipCode, relatedPersonRelationship, industryGroupType, revenueRange, federalExemptionsExclusions, isAmendment, dateOfFirstSale, durationOfOfferingIsMoreThanYear, securitiesOfferedAreOfEquityType, isBusinessCombinationTransaction, minimumInvestmentAccepted, totalOfferingAmount, totalAmountSold, totalAmountRemaining, hasNonAccreditedInvestors, totalNumberAlreadyInvested, salesCommissions, findersFees, grossProceedsUsed

	// CRYPTO
	// 'cryptocurrencyList', // Retrieves a list of all cryptocurrencies. (No parameters.) -> symbol, name, exchange, icoDate, circulatingSupply, totalSupply
	// 'cryptocurrencyQuote', // Retrieves a full real-time quote for a cryptocurrency. (symbol) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	// 'cryptocurrencyQuoteShort', // Retrieves a short real-time quote for a cryptocurrency. (symbol) -> symbol, price, change, volume
	// 'allCryptocurrenciesQuotes', // Retrieves real-time quotes for multiple cryptocurrencies. (options (short)) -> No specific return fields selectable, returns full object/array.
	// 'cryptocurrencyChartLight', // Retrieves light historical end-of-day price data for a cryptocurrency. (symbol; options (from, to)) -> symbol, date, price, volume
	// 'cryptocurrencyChartFull', // Retrieves full historical end-of-day price data for a cryptocurrency. (symbol; options (from, to)) -> symbol, change, changePercent, vwap, date, open, high, low, close, volume
	// 'cryptocurrencyChart1Min', // Retrieves 1-minute interval historical cryptocurrency chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'cryptocurrencyChart5Min', // Retrieves 5-minute interval historical cryptocurrency chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'cryptocurrencyChart1Hour', // Retrieves 1-hour interval historical cryptocurrency chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume

	// FOREX
	// 'forexList', // Retrieves a list of all Forex currency pairs. (No parameters.) -> symbol, fromCurrency, toCurrency, fromName, toName
	// 'forexQuote', // Retrieves a real-time quote for a Forex currency pair. (symbol) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	// 'forexQuoteShort', // Retrieves a short real-time quote for a Forex currency pair. (symbol) -> symbol, price, change, volume
	// 'allForexQuotes', // Retrieves real-time quotes for multiple Forex pairs. (options (short)) -> No specific return fields selectable, returns full object/array.
	// 'forexChartLight', // Retrieves light historical end-of-day price data for a Forex pair. (symbol; options (from, to)) -> symbol, date, price, volume
	// 'forexChartFull', // Retrieves full historical end-of-day price data for a Forex pair. (symbol; options (from, to)) -> symbol, change, changePercent, vwap, date, open, high, low, close, volume
	// 'forexChart1Min', // Retrieves 1-minute interval historical Forex chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'forexChart5Min', // Retrieves 5-minute interval historical Forex chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'forexChart1Hour', // Retrieves 1-hour interval historical Forex chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume

	// FINANCIAL STATEMENTS
	'incomeStatement', // Retrieves income statements for a company. (symbol; options (limit, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, revenue, costOfRevenue, grossProfit, researchAndDevelopmentExpenses, generalAndAdministrativeExpenses, sellingAndMarketingExpenses, sellingGeneralAndAdministrativeExpenses, otherExpenses, operatingExpenses, costAndExpenses, netInterestIncome, interestIncome, interestExpense, depreciationAndAmortization, ebitda, ebit, nonOperatingIncomeExcludingInterest, operatingIncome, totalOtherIncomeExpensesNet, incomeBeforeTax, incomeTaxExpense, netIncomeFromContinuingOperations, netIncomeFromDiscontinuedOperations, otherAdjustmentsToNetIncome, netIncome, netIncomeDeductions, bottomLineNetIncome, eps, epsDiluted, weightedAverageShsOut, weightedAverageShsOutDil
	'balanceSheetStatement', // Retrieves balance sheet statements for a company. (symbol; options (limit, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, cashAndCashEquivalents, shortTermInvestments, cashAndShortTermInvestments, netReceivables, accountsReceivables, otherReceivables, inventory, prepaids, otherCurrentAssets, totalCurrentAssets, propertyPlantEquipmentNet, goodwill, intangibleAssets, goodwillAndIntangibleAssets, longTermInvestments, taxAssets, otherNonCurrentAssets, totalNonCurrentAssets, otherAssets, totalAssets, totalPayables, accountPayables, otherPayables, accruedExpenses, shortTermDebt, capitalLeaseObligationsCurrent, taxPayables, deferredRevenue, otherCurrentLiabilities, totalCurrentLiabilities, longTermDebt, deferredRevenueNonCurrent, deferredTaxLiabilitiesNonCurrent, otherNonCurrentLiabilities, totalNonCurrentLiabilities, otherLiabilities, capitalLeaseObligations, totalLiabilities, treasuryStock, preferredStock, commonStock, retainedEarnings, additionalPaidInCapital, accumulatedOtherComprehensiveIncomeLoss, otherTotalStockholdersEquity, totalStockholdersEquity, totalEquity, minorityInterest, totalLiabilitiesAndTotalEquity, totalInvestments, totalDebt, netDebt
	'cashFlowStatement', // Retrieves cash flow statements for a company. (symbol; options (limit, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, netIncome, depreciationAndAmortization, deferredIncomeTax, stockBasedCompensation, changeInWorkingCapital, accountsReceivables, inventory, accountsPayables, otherWorkingCapital, otherNonCashItems, netCashProvidedByOperatingActivities, investmentsInPropertyPlantAndEquipment, acquisitionsNet, purchasesOfInvestments, salesMaturitiesOfInvestments, otherInvestingActivities, netCashProvidedByInvestingActivities, netDebtIssuance, longTermNetDebtIssuance, shortTermNetDebtIssuance, netStockIssuance, netCommonStockIssuance, commonStockIssuance, commonStockRepurchased, netPreferredStockIssuance, netDividendsPaid, commonDividendsPaid, preferredDividendsPaid, otherFinancingActivities, netCashProvidedByFinancingActivities, effectOfForexChangesOnCash, netChangeInCash, cashAtEndOfPeriod, cashAtBeginningOfPeriod, operatingCashFlow, capitalExpenditure, freeCashFlow, incomeTaxesPaid, interestPaid
	// 'latestFinancialStatements', // Retrieves metadata for the latest available financial statements. (options (page, limit)) -> symbol, calendarYear, period, date, dateAdded
	'incomeStatementTtm', // Retrieves Trailing Twelve Months (TTM) income statements for a company. (symbol; options (limit)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, revenue, costOfRevenue, grossProfit, researchAndDevelopmentExpenses, generalAndAdministrativeExpenses, sellingAndMarketingExpenses, sellingGeneralAndAdministrativeExpenses, otherExpenses, operatingExpenses, costAndExpenses, netInterestIncome, interestIncome, interestExpense, depreciationAndAmortization, ebitda, ebit, nonOperatingIncomeExcludingInterest, operatingIncome, totalOtherIncomeExpensesNet, incomeBeforeTax, incomeTaxExpense, netIncomeFromContinuingOperations, netIncomeFromDiscontinuedOperations, otherAdjustmentsToNetIncome, netIncome, netIncomeDeductions, bottomLineNetIncome, eps, epsDiluted, weightedAverageShsOut, weightedAverageShsOutDil
	'balanceSheetStatementTtm', // Retrieves Trailing Twelve Months (TTM) balance sheet statements for a company. (symbol; options (limit)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, cashAndCashEquivalents, shortTermInvestments, cashAndShortTermInvestments, netReceivables, accountsReceivables, otherReceivables, inventory, prepaids, otherCurrentAssets, totalCurrentAssets, propertyPlantEquipmentNet, goodwill, intangibleAssets, goodwillAndIntangibleAssets, longTermInvestments, taxAssets, otherNonCurrentAssets, totalNonCurrentAssets, otherAssets, totalAssets, totalPayables, accountPayables, otherPayables, accruedExpenses, shortTermDebt, capitalLeaseObligationsCurrent, taxPayables, deferredRevenue, otherCurrentLiabilities, totalCurrentLiabilities, longTermDebt, deferredRevenueNonCurrent, deferredTaxLiabilitiesNonCurrent, otherNonCurrentLiabilities, totalNonCurrentLiabilities, otherLiabilities, capitalLeaseObligations, totalLiabilities, treasuryStock, preferredStock, commonStock, retainedEarnings, additionalPaidInCapital, accumulatedOtherComprehensiveIncomeLoss, otherTotalStockholdersEquity, totalStockholdersEquity, totalEquity, minorityInterest, totalLiabilitiesAndTotalEquity, totalInvestments, totalDebt, netDebt
	'cashFlowStatementTtm', // Retrieves Trailing Twelve Months (TTM) cash flow statements for a company. (symbol; options (limit)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, netIncome, depreciationAndAmortization, deferredIncomeTax, stockBasedCompensation, changeInWorkingCapital, accountsReceivables, inventory, accountsPayables, otherWorkingCapital, otherNonCashItems, netCashProvidedByOperatingActivities, investmentsInPropertyPlantAndEquipment, acquisitionsNet, purchasesOfInvestments, salesMaturitiesOfInvestments, otherInvestingActivities, netCashProvidedByInvestingActivities, netDebtIssuance, longTermNetDebtIssuance, shortTermNetDebtIssuance, netStockIssuance, netCommonStockIssuance, commonStockIssuance, commonStockRepurchased, netPreferredStockIssuance, netDividendsPaid, commonDividendsPaid, preferredDividendsPaid, otherFinancingActivities, netCashProvidedByFinancingActivities, effectOfForexChangesOnCash, netChangeInCash, cashAtEndOfPeriod, cashAtBeginningOfPeriod, operatingCashFlow, capitalExpenditure, freeCashFlow, incomeTaxesPaid, interestPaid
	'keyMetrics', // Retrieves key financial metrics for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, marketCap, enterpriseValue, evToSales, evToOperatingCashFlow, evToFreeCashFlow, evToEBITDA, netDebtToEBITDA, currentRatio, incomeQuality, grahamNumber, grahamNetNet, taxBurden, interestBurden, workingCapital, investedCapital, returnOnAssets, operatingReturnOnAssets, returnOnTangibleAssets, returnOnEquity, returnOnInvestedCapital, returnOnCapitalEmployed, earningsYield, freeCashFlowYield, capexToOperatingCashFlow, capexToDepreciation, capexToRevenue, salesGeneralAndAdministrativeToRevenue, researchAndDevelopementToRevenue, stockBasedCompensationToRevenue, intangiblesToTotalAssets, averageReceivables, averagePayables, averageInventory, daysOfSalesOutstanding, daysOfPayablesOutstanding, daysOfInventoryOutstanding, operatingCycle, cashConversionCycle, freeCashFlowToEquity, freeCashFlowToFirm, tangibleAssetValue, netCurrentAssetValue
	'financialRatios', // Retrieves financial ratios for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, grossProfitMargin, ebitMargin, ebitdaMargin, operatingProfitMargin, pretaxProfitMargin, continuousOperationsProfitMargin, netProfitMargin, bottomLineProfitMargin, receivablesTurnover, payablesTurnover, inventoryTurnover, fixedAssetTurnover, assetTurnover, currentRatio, quickRatio, solvencyRatio, cashRatio, priceToEarningsRatio, priceToEarningsGrowthRatio, forwardPriceToEarningsGrowthRatio, priceToBookRatio, priceToSalesRatio, priceToFreeCashFlowRatio, priceToOperatingCashFlowRatio, debtToAssetsRatio, debtToEquityRatio, debtToCapitalRatio, longTermDebtToCapitalRatio, financialLeverageRatio, workingCapitalTurnoverRatio, operatingCashFlowRatio, operatingCashFlowSalesRatio, freeCashFlowOperatingCashFlowRatio, debtServiceCoverageRatio, interestCoverageRatio, shortTermOperatingCashFlowCoverageRatio, operatingCashFlowCoverageRatio, capitalExpenditureCoverageRatio, dividendPaidAndCapexCoverageRatio, dividendPayoutRatio, dividendYield, dividendYieldPercentage, revenuePerShare, netIncomePerShare, interestDebtPerShare, cashPerShare, bookValuePerShare, tangibleBookValuePerShare, shareholdersEquityPerShare, operatingCashFlowPerShare, capexPerShare, freeCashFlowPerShare, netIncomePerEBT, ebtPerEbit, priceToFairValue, debtToMarketCap, effectiveTaxRate, enterpriseValueMultiple
	'keyMetricsTtm', // Retrieves Trailing Twelve Months (TTM) key financial metrics for a company. (symbol) -> symbol, marketCap, marketCapTTM, enterpriseValueTTM, evToSalesTTM, evToOperatingCashFlowTTM, evToFreeCashFlowTTM, evToEBITDATTM, netDebtToEBITDATTM, currentRatioTTM, incomeQualityTTM, grahamNumberTTM, grahamNetNetTTM, taxBurdenTTM, interestBurdenTTM, workingCapitalTTM, investedCapitalTTM, returnOnAssetsTTM, operatingReturnOnAssetsTTM, returnOnTangibleAssetsTTM, returnOnEquityTTM, returnOnInvestedCapitalTTM, returnOnCapitalEmployedTTM, earningsYieldTTM, freeCashFlowYieldTTM, capexToOperatingCashFlowTTM, capexToDepreciationTTM, capexToRevenueTTM, salesGeneralAndAdministrativeToRevenueTTM, researchAndDevelopementToRevenueTTM, stockBasedCompensationToRevenueTTM, intangiblesToTotalAssetsTTM, averageReceivablesTTM, averagePayablesTTM, averageInventoryTTM, daysOfSalesOutstandingTTM, daysOfPayablesOutstandingTTM, daysOfInventoryOutstandingTTM, operatingCycleTTM, cashConversionCycleTTM, freeCashFlowToEquityTTM, freeCashFlowToFirmTTM, tangibleAssetValueTTM, netCurrentAssetValueTTM
	'financialRatiosTtm', // Retrieves Trailing Twelve Months (TTM) financial ratios for a company. (symbol) -> symbol, grossProfitMarginTTM, ebitMarginTTM, ebitdaMarginTTM, operatingProfitMarginTTM, pretaxProfitMarginTTM, continuousOperationsProfitMarginTTM, netProfitMarginTTM, bottomLineProfitMarginTTM, receivablesTurnoverTTM, payablesTurnoverTTM, inventoryTurnoverTTM, fixedAssetTurnoverTTM, assetTurnoverTTM, currentRatioTTM, quickRatioTTM, solvencyRatioTTM, cashRatioTTM, priceToEarningsRatioTTM, priceToEarningsGrowthRatioTTM, forwardPriceToEarningsGrowthRatioTTM, priceToBookRatioTTM, priceToSalesRatioTTM, priceToFreeCashFlowRatioTTM, priceToOperatingCashFlowRatioTTM, debtToAssetsRatioTTM, debtToEquityRatioTTM, debtToCapitalRatioTTM, longTermDebtToCapitalRatioTTM, financialLeverageRatioTTM, workingCapitalTurnoverRatioTTM, operatingCashFlowRatioTTM, operatingCashFlowSalesRatioTTM, freeCashFlowOperatingCashFlowRatioTTM, debtServiceCoverageRatioTTM, interestCoverageRatioTTM, shortTermOperatingCashFlowCoverageRatioTTM, operatingCashFlowCoverageRatioTTM, capitalExpenditureCoverageRatioTTM, dividendPaidAndCapexCoverageRatioTTM, dividendPayoutRatioTTM, dividendYieldTTM, dividendYieldPercentageTTM, enterpriseValueTTM, revenuePerShareTTM, netIncomePerShareTTM, interestDebtPerShareTTM, cashPerShareTTM, bookValuePerShareTTM, tangibleBookValuePerShareTTM, shareholdersEquityPerShareTTM, operatingCashFlowPerShareTTM, capexPerShareTTM, freeCashFlowPerShareTTM, netIncomePerEBTTTM, ebtPerEbitTTM, priceToFairValueTTM, debtToMarketCapTTM, effectiveTaxRateTTM, enterpriseValueMultipleTTM
	'financialScores', // Retrieves financial health scores (Altman Z-Score, Piotroski Score) for a company. (symbol) -> symbol, reportedCurrency, altmanZScore, piotroskiScore, workingCapital, totalAssets, retainedEarnings, ebit, marketCap, totalLiabilities, revenue
	'ownerEarnings', // Retrieves owner earnings for a company. (symbol; options (limit)) -> symbol, reportedCurrency, fiscalYear, period, date, averagePPE, maintenanceCapex, ownersEarnings, growthCapex, ownersEarningsPerShare
	'enterpriseValues', // Retrieves enterprise values for a company. (symbol; options (limit, period)) -> symbol, date, stockPrice, numberOfShares, marketCapitalization, minusCashAndCashEquivalents, addTotalDebt, enterpriseValue
	'incomeStatementGrowth', // Retrieves income statement growth metrics for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthRevenue, growthCostOfRevenue, growthGrossProfit, growthGrossProfitRatio, growthResearchAndDevelopmentExpenses, growthGeneralAndAdministrativeExpenses, growthSellingAndMarketingExpenses, growthOtherExpenses, growthOperatingExpenses, growthCostAndExpenses, growthInterestIncome, growthInterestExpense, growthDepreciationAndAmortization, growthEBITDA, growthOperatingIncome, growthIncomeBeforeTax, growthIncomeTaxExpense, growthNetIncome, growthEPS, growthEPSDiluted, growthWeightedAverageShsOut, growthWeightedAverageShsOutDil, growthEBIT, growthNonOperatingIncomeExcludingInterest, growthNetInterestIncome, growthTotalOtherIncomeExpensesNet, growthNetIncomeFromContinuingOperations, growthOtherAdjustmentsToNetIncome, growthNetIncomeDeductions
	'balanceSheetStatementGrowth', // Retrieves balance sheet statement growth metrics for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthCashAndCashEquivalents, growthShortTermInvestments, growthCashAndShortTermInvestments, growthNetReceivables, growthInventory, growthOtherCurrentAssets, growthTotalCurrentAssets, growthPropertyPlantEquipmentNet, growthGoodwill, growthIntangibleAssets, growthGoodwillAndIntangibleAssets, growthLongTermInvestments, growthTaxAssets, growthOtherNonCurrentAssets, growthTotalNonCurrentAssets, growthOtherAssets, growthTotalAssets, growthAccountPayables, growthShortTermDebt, growthTaxPayables, growthDeferredRevenue, growthOtherCurrentLiabilities, growthTotalCurrentLiabilities, growthLongTermDebt, growthDeferredRevenueNonCurrent, growthDeferredTaxLiabilitiesNonCurrent, growthOtherNonCurrentLiabilities, growthTotalNonCurrentLiabilities, growthOtherLiabilities, growthTotalLiabilities, growthPreferredStock, growthCommonStock, growthRetainedEarnings, growthAccumulatedOtherComprehensiveIncomeLoss, growthOthertotalStockholdersEquity, growthTotalStockholdersEquity, growthMinorityInterest, growthTotalEquity, growthTotalLiabilitiesAndStockholdersEquity, growthTotalInvestments, growthTotalDebt, growthNetDebt, growthAccountsReceivables, growthOtherReceivables, growthPrepaids, growthTotalPayables, growthOtherPayables, growthAccruedExpenses, growthCapitalLeaseObligationsCurrent, growthAdditionalPaidInCapital, growthTreasuryStock
	'cashFlowStatementGrowth', // Retrieves cash flow statement growth metrics for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthNetIncome, growthDepreciationAndAmortization, growthDeferredIncomeTax, growthStockBasedCompensation, growthChangeInWorkingCapital, growthAccountsReceivables, growthInventory, growthAccountsPayables, growthOtherWorkingCapital, growthOtherNonCashItems, growthNetCashProvidedByOperatingActivites, growthInvestmentsInPropertyPlantAndEquipment, growthAcquisitionsNet, growthPurchasesOfInvestments, growthSalesMaturitiesOfInvestments, growthOtherInvestingActivites, growthNetCashUsedForInvestingActivites, growthDebtRepayment, growthCommonStockIssued, growthCommonStockRepurchased, growthDividendsPaid, growthOtherFinancingActivites, growthNetCashUsedProvidedByFinancingActivities, growthEffectOfForexChangesOnCash, growthNetChangeInCash, growthCashAtEndOfPeriod, growthCashAtBeginningOfPeriod, growthOperatingCashFlow, growthCapitalExpenditure, growthFreeCashFlow, growthNetDebtIssuance, growthLongTermNetDebtIssuance, growthShortTermNetDebtIssuance, growthNetStockIssuance, growthPreferredDividendsPaid, growthIncomeTaxesPaid, growthInterestPaid
	'financialStatementGrowth', // Retrieves overall financial statement growth metrics for a company. (symbol; options (limit, period)) -> symbol, date, fiscalYear, period, reportedCurrency, revenueGrowth, grossProfitGrowth, ebitgrowth, operatingIncomeGrowth, netIncomeGrowth, epsgrowth, epsdilutedGrowth, weightedAverageSharesGrowth, weightedAverageSharesDilutedGrowth, dividendsPerShareGrowth, operatingCashFlowGrowth, receivablesGrowth, inventoryGrowth, assetGrowth, bookValueperShareGrowth, debtGrowth, rdexpenseGrowth, sgaexpensesGrowth, freeCashFlowGrowth, tenYRevenueGrowthPerShare, fiveYRevenueGrowthPerShare, threeYRevenueGrowthPerShare, tenYOperatingCFGrowthPerShare, fiveYOperatingCFGrowthPerShare, threeYOperatingCFGrowthPerShare, tenYNetIncomeGrowthPerShare, fiveYNetIncomeGrowthPerShare, threeYNetIncomeGrowthPerShare, tenYShareholdersEquityGrowthPerShare, fiveYShareholdersEquityGrowthPerShare, threeYShareholdersEquityGrowthPerShare, tenYDividendperShareGrowthPerShare, fiveYDividendperShareGrowthPerShare, threeYDividendperShareGrowthPerShare, ebitdaGrowth, growthCapitalExpenditure, tenYBottomLineNetIncomeGrowthPerShare, fiveYBottomLineNetIncomeGrowthPerShare, threeYBottomLineNetIncomeGrowthPerShare
	// 'financialReportsDates', // Retrieves dates and links for available financial reports for a company. (symbol) -> symbol, fiscalYear, period, linkXlsx, linkJson
	// 'financialReportJson', // Retrieves a company's annual (10-K) or quarterly (10-Q) report in JSON format. (symbol; options (year, period)) -> symbol, period, year, data
	// 'financialReportXlsx', // Retrieves a company's annual (10-K) or quarterly (10-Q) report in XLSX format (returns metadata with link). (symbol; options (year, period)) -> symbol, period, year, data
	'revenueProductSegmentation', // Retrieves revenue breakdown by product line for a company. (symbol; options (period, structure)) -> symbol, fiscalYear, period, reportedCurrency, date, data
	'revenueGeographicSegmentation', // Retrieves revenue breakdown by geographic region for a company. (symbol; options (period, structure)) -> symbol, fiscalYear, period, reportedCurrency, date, data
	// 'asReportedIncomeStatements', // Retrieves income statements as reported by the company. (symbol; options (limit, period)) -> symbol, fiscalYear, period, reportedCurrency, date, data
	// 'asReportedBalanceStatements', // Retrieves balance sheet statements as reported by the company. (symbol; options (limit, period)) -> symbol, fiscalYear, period, reportedCurrency, date, data
	// 'asReportedCashFlowStatements', // Retrieves cash flow statements as reported by the company. (symbol; options (limit, period)) -> symbol, fiscalYear, period, reportedCurrency, date, data
	// 'fullAsReportedFinancialStatements', // Retrieves full financial statements (income, balance sheet, cash flow) as reported by the company. (symbol; options (limit, period)) -> symbol, fiscalYear, period, reportedCurrency, date, data

	// FORM 13F
	// 'latestInstitutionalOwnershipFilings', // Retrieves the latest institutional ownership (Form 13F) filings. (options (page, limit)) -> cik, name, date, filingDate, acceptedDate, formType, link, finalLink
	// 'secFilingsExtract', // Extracts detailed data from SEC Form 13F filings. (options (cik, year, quarter)) -> date, filingDate, acceptedDate, cik, securityCusip, symbol, nameOfIssuer, shares, titleOfClass, sharesType, putCallShare, value, link, finalLink
	// 'form13FFilingDates', // Retrieves dates associated with Form 13F filings by an institutional investor. (cik) -> date, year, quarter
	'filingsExtractAnalyticsByHolder', // Retrieves an analytical breakdown of institutional filings by holder for a specific stock. (options (symbol, year, quarter, page, limit)) -> date, cik, filingDate, investorName, symbol, securityName, typeOfSecurity, securityCusip, sharesType, putCallShare, investmentDiscretion, industryTitle, weight, lastWeight, changeInWeight, changeInWeightPercentage, marketValue, lastMarketValue, changeInMarketValue, changeInMarketValuePercentage, sharesNumber, lastSharesNumber, changeInSharesNumber, changeInSharesNumberPercentage, quarterEndPrice, avgPricePaid, isNew, isSoldOut, ownership, lastOwnership, changeInOwnership, changeInOwnershipPercentage, holdingPeriod, firstAdded, performance, performancePercentage, lastPerformance, changeInPerformance, isCountedForPerformance
	'holderPerformanceSummary', // Retrieves a performance summary for an institutional investor. (options (cik, page)) -> date, cik, investorName, portfolioSize, securitiesAdded, securitiesRemoved, marketValue, previousMarketValue, changeInMarketValue, changeInMarketValuePercentage, averageHoldingPeriod, averageHoldingPeriodTop10, averageHoldingPeriodTop20, turnover, turnoverAlternateSell, turnoverAlternateBuy, performance, performancePercentage, lastPerformance, changeInPerformance, performance1year, performancePercentage1year, performance3year, performancePercentage3year, performance5year, performancePercentage5year, performanceSinceInception, performanceSinceInceptionPercentage, performanceRelativeToSP500Percentage, performance1yearRelativeToSP500Percentage, performance3yearRelativeToSP500Percentage, performance5yearRelativeToSP500Percentage, performanceSinceInceptionRelativeToSP500Percentage
	'holdersIndustryBreakdown', // Retrieves the industry breakdown of an institutional investor's holdings. (options (cik, year, quarter)) -> date, cik, investorName, industryTitle, weight, lastWeight, changeInWeight, changeInWeightPercentage, performance, performancePercentage, lastPerformance, changeInPerformance
	'positionsSummary', // Retrieves a summary of institutional holdings for a specific stock symbol. (options (symbol, year, quarter)) -> symbol, cik, date, investorsHolding, lastInvestorsHolding, investorsHoldingChange, numberOf13Fshares, lastNumberOf13Fshares, numberOf13FsharesChange, totalInvested, lastTotalInvested, totalInvestedChange, ownershipPercent, lastOwnershipPercent, ownershipPercentChange, newPositions, lastNewPositions, newPositionsChange, increasedPositions, lastIncreasedPositions, increasedPositionsChange, closedPositions, lastClosedPositions, closedPositionsChange, reducedPositions, lastReducedPositions, reducedPositionsChange, totalCalls, lastTotalCalls, totalCallsChange, totalPuts, lastTotalPuts, totalPutsChange, putCallRatio, lastPutCallRatio, putCallRatioChange
	'industryPerformanceSummary', // Retrieves a summary of financial performance by industry. (options (year, quarter)) -> industryTitle, industryValue, date

	// INDEXES
	// 'indexesList', // Retrieves a list of stock market indexes. (No parameters.) -> symbol, name, exchange, currency
	'indexQuote', // Retrieves a real-time quote for a stock market index. (symbol) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	// 'indexQuoteShort', // Retrieves a short real-time quote for a stock market index. (symbol) -> symbol, price, change, volume
	// 'allIndexQuotes', // Retrieves real-time quotes for multiple stock market indexes. (options (short)) -> No specific return fields selectable, returns full object/array.
	// 'indexChartLight', // Retrieves light historical end-of-day price data for an index. (symbol; options (from, to)) -> symbol, date, price, volume
	'indexChartFull', // Retrieves full historical end-of-day price data for an index. (symbol; options (from, to)) -> symbol, change, changePercent, vwap, date, open, high, low, close, volume
	// 'indexChart1Min', // Retrieves 1-minute interval historical index chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'indexChart5Min', // Retrieves 5-minute interval historical index chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'indexChart1Hour', // Retrieves 1-hour interval historical index chart data. (symbol; options (from, to)) -> date, open, high, low, close, volume
	// 'sp500Constituents', // Retrieves the current constituents of the S&P 500 index. (No parameters.) -> symbol, name, sector, subSector, headQuarter, dateFirstAdded, cik, founded
	// 'nasdaqConstituents', // Retrieves the current constituents of the Nasdaq index. (No parameters.) -> symbol, name, sector, subSector, headQuarter, dateFirstAdded, cik, founded
	// 'dowJonesConstituents', // Retrieves the current constituents of the Dow Jones Industrial Average. (No parameters.) -> symbol, name, sector, subSector, headQuarter, dateFirstAdded, cik, founded
	// 'historicalSp500Constituents', // Retrieves historical changes to the S&P 500 index constituents. (No parameters.) -> dateAdded, addedSecurity, removedTicker, removedSecurity, date, symbol, reason
	// 'historicalNasdaqConstituents', // Retrieves historical changes to the Nasdaq index constituents. (No parameters.) -> dateAdded, addedSecurity, removedTicker, removedSecurity, date, symbol, reason
	// 'historicalDowJonesConstituents', // Retrieves historical changes to the Dow Jones Industrial Average constituents. (No parameters.) -> dateAdded, addedSecurity, removedTicker, removedSecurity, date, symbol, reason

	// INSIDER TRADES
	'latestInsiderTrades', // Retrieves the latest insider trading activity. (options (date, page, limit)) -> symbol, filingDate, transactionDate, reportingCik, companyCik, transactionType, securitiesOwned, reportingName, typeOfOwner, acquisitionOrDisposition, directOrIndirect, formType, securitiesTransacted, price, securityName, url
	'searchInsiderTrades', // Searches insider trading activity with various filters. (options (symbol, page, limit, reportingCik, companyCik, transactionType)) -> symbol, filingDate, transactionDate, reportingCik, companyCik, transactionType, securitiesOwned, reportingName, typeOfOwner, acquisitionOrDisposition, directOrIndirect, formType, securitiesTransacted, price, securityName, url
	'searchInsiderTradesByReportingName', // Searches for insider trading activity by reporting name. (name) -> reportingCik, reportingName
	'allInsiderTransactionTypes', // Retrieves a list of all insider transaction types. (No parameters.) -> transactionType
	'insiderTradeStatistics', // Retrieves statistics on insider trading activity for a specific company. (symbol) -> symbol, cik, year, quarter, acquiredTransactions, disposedTransactions, acquiredDisposedRatio, totalAcquired, totalDisposed, averageAcquired, averageDisposed, totalPurchases, totalSales
	'acquisitionOwnership', // Tracks changes in stock ownership during acquisitions (SC 13D/G filings). (symbol; options (limit)) -> cik, symbol, filingDate, acceptedDate, cusip, nameOfReportingPerson, citizenshipOrPlaceOfOrganization, soleVotingPower, sharedVotingPower, soleDispositivePower, sharedDispositivePower, amountBeneficiallyOwned, percentOfClass, typeOfReportingPerson, url

	// MARKET PERFORMANCE
	// 'marketSectorPerformanceSnapshot', // Retrieves a snapshot of market sector performance for a specific date. (options (date, exchange, sector, industry)) -> date, sector, exchange, averageChange
	// 'marketIndustryPerformanceSnapshot', // Retrieves a snapshot of market industry performance for a specific date. (options (date, exchange, sector, industry)) -> date, industry, exchange, averageChange
	// 'historicalMarketSectorPerformance', // Retrieves historical market sector performance data. (sector; options (from, to, exchange)) -> date, sector, exchange, averageChange
	// 'historicalMarketIndustryPerformance', // Retrieves historical market industry performance data. (industry; options (from, to, exchange)) -> date, industry, exchange, averageChange
	// 'marketSectorPESnapshot', // Retrieves a snapshot of Price-to-Earnings (P/E) ratios for market sectors. (options (date, exchange, sector, industry)) -> date, sector, exchange, pe
	// 'marketIndustryPESnapshot', // Retrieves a snapshot of Price-to-Earnings (P/E) ratios for market industries. (options (date, exchange, sector, industry)) -> date, industry, exchange, pe
	// 'historicalMarketSectorPE', // Retrieves historical Price-to-Earnings (P/E) ratios for market sectors. (sector; options (from, to, exchange)) -> date, sector, exchange, pe
	// 'historicalMarketIndustryPE', // Retrieves historical Price-to-Earnings (P/E) ratios for market industries. (industry; options (from, to, exchange)) -> date, industry, exchange, pe
	// 'biggestStockGainers', // Retrieves a list of the biggest stock gainers for the current trading day. (No parameters.) -> symbol, price, name, change, changesPercentage, exchange
	// 'biggestStockLosers', // Retrieves a list of the biggest stock losers for the current trading day. (No parameters.) -> symbol, price, name, change, changesPercentage, exchange
	// 'topTradedStocks', // Retrieves a list of the most actively traded stocks for the current trading day. (No parameters.) -> symbol, price, name, change, changesPercentage, exchange

	// MARKET HOURS
	// 'exchangeMarketHours', // Retrieves trading hours for a specific stock exchange. (exchange) -> exchange, name, openingHour, closingHour, timezone, isMarketOpen
	// 'allExchangeMarketHours', // Retrieves trading hours for all supported stock exchanges. (No parameters.) -> exchange, name, openingHour, closingHour, timezone, isMarketOpen

	// NEWS
	// 'fmpArticles', // Retrieves the latest articles from Financial Modeling Prep. (options (page, limit)) -> title, date, content, tickers, image, link, author, site
	// 'generalNews', // Retrieves the latest general news articles. (options (from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'pressReleases', // Retrieves the latest press releases from companies. (options (from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'stockNews', // Retrieves the latest stock market news. (options (from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'cryptoNews', // Retrieves the latest cryptocurrency news. (options (from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'forexNews', // Retrieves the latest Forex news. (options (from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'searchPressReleases', // Searches for press releases related to specific stock symbols. (options (symbols, from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'searchStockNews', // Searches for stock news related to specific stock symbols. (options (symbols, from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'searchCryptoNews', // Searches for cryptocurrency news related to specific crypto symbols. (options (symbols, from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url
	// 'searchForexNews', // Searches for Forex news related to specific currency pairs. (options (symbols, from, to, page, limit)) -> symbol, publishedDate, publisher, title, image, site, text, url

	// TECHNICAL INDICATORS
	'simpleMovingAverage', // Retrieves Simple Moving Average (SMA) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> sma, date, open, high, low, close, volume
	'exponentialMovingAverage', // Retrieves Exponential Moving Average (EMA) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> ema, date, open, high, low, close, volume
	'weightedMovingAverage', // Retrieves Weighted Moving Average (WMA) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> wma, date, open, high, low, close, volume
	'doubleExponentialMovingAverage', // Retrieves Double Exponential Moving Average (DEMA) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> dema, date, open, high, low, close, volume
	'tripleExponentialMovingAverage', // Retrieves Triple Exponential Moving Average (TEMA) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> tema, date, open, high, low, close, volume
	'relativeStrengthIndex', // Retrieves Relative Strength Index (RSI) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> rsi, date, open, high, low, close, volume
	'standardDeviation', // Retrieves Standard Deviation data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> standardDeviation, date, open, high, low, close, volume
	'williamsPercentR', // Retrieves Williams %R data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> williams, date, open, high, low, close, volume
	'averageDirectionalIndex', // Retrieves Average Directional Index (ADX) data for a symbol. (symbol; options (periodLength, timeframe, from, to)) -> adx, date, open, high, low, close, volume

	// QUOTE
	'stockQuote', // Retrieves a real-time stock quote. (symbol) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	'stockQuoteShort', // Retrieves a short real-time stock quote. (symbol) -> symbol, price, change, volume
	'aftermarketTrade', // Retrieves real-time aftermarket trade data for a stock. (symbol) -> symbol, price, tradeSize, timestamp
	'aftermarketQuote', // Retrieves real-time aftermarket quote data for a stock. (symbol) -> symbol, bidSize, bidPrice, askSize, askPrice, volume, timestamp
	'stockPriceChange', // Retrieves stock price change percentages over various time periods. (symbol) -> symbol, 1D, 5D, 1M, 3M, 6M, ytd, 1Y, 3Y, 5Y, 10Y, max
	// 'stockBatchQuote', // Retrieves real-time stock quotes for multiple symbols. (symbols) -> symbol, name, price, changesPercentage, change, dayLow, dayHigh, yearHigh, yearLow, marketCap, priceAvg50, priceAvg200, exchange, volume, avgVolume, open, previousClose, eps, pe, earningsAnnouncement, sharesOutstanding, timestamp
	// 'stockBatchQuoteShort', // Retrieves short real-time stock quotes for multiple symbols. (symbols) -> symbol, price, change, volume
	// 'batchAftermarketTrade', // Retrieves real-time aftermarket trade data for multiple stocks. (symbols) -> symbol, price, tradeSize, timestamp
	// 'batchAftermarketQuote', // Retrieves real-time aftermarket quote data for multiple stocks. (symbols) -> symbol, bidSize, bidPrice, askSize, askPrice, volume, timestamp
	'exchangeStockQuotes', // Retrieves real-time stock quotes for all stocks on a specific exchange. (exchange; options (short)) -> No specific return fields selectable, returns full object/array.
	'mutualFundQuotes', // Retrieves real-time quotes for all mutual funds. (options (short)) -> No specific return fields selectable, returns full object/array.
	'etfQuotes', // Retrieves real-time quotes for all ETFs. (options (short)) -> No specific return fields selectable, returns full object/array.

	// EARNINGS TRANSCRIPT
	// 'latestEarningTranscripts', // Retrieves metadata for the latest available earnings transcripts. (options (limit, page)) -> symbol, period, fiscalYear, date
	// 'earningsTranscript', // Retrieves the full transcript of a company's earnings call. (symbol; options (year, quarter, limit)) -> symbol, period, year, date, content
	'earningsTranscriptDatesBySymbol', // Retrieves available earnings call transcript dates for a specific company. (symbol) -> quarter, fiscalYear, date
	// 'earningsTranscriptList', // Retrieves a list of companies with available earnings transcripts. (No parameters.) -> symbol, companyName, noOfTranscripts

	// SEC FILINGS
	'getSecFiling', // Fetches the raw HTML/text content of an SEC filing from the SEC's EDGAR system directly. (url) -> Returns the raw text content of the SEC filing.
	// 'latest8kSecFilings', // Retrieves the latest 8-K SEC filings within a date range. (options (from, to, page, limit)) -> symbol, cik, filingDate, acceptedDate, formType, hasFinancials, link, finalLink
	// 'latestSecFilingsWithFinancials', // Retrieves the latest SEC filings with financials (e.g., 10-K, 10-Q) within a date range. (options (from, to, page, limit)) -> symbol, cik, filingDate, acceptedDate, formType, hasFinancials, link, finalLink
	// 'searchSecFilingsByFormType', // Searches SEC filings by form type within a date range. (options (formType, from, to, page, limit)) -> symbol, cik, filingDate, acceptedDate, formType, hasFinancials, link, finalLink
	// 'searchSecFilingsBySymbol', // Searches SEC filings by company symbol within a date range. (options (symbol, from, to, page, limit)) -> symbol, cik, filingDate, acceptedDate, formType, hasFinancials, link, finalLink
	// 'searchSecFilingsByCik', // Searches SEC filings by CIK within a date range. (options (cik, from, to, page, limit)) -> symbol, cik, filingDate, acceptedDate, formType, hasFinancials, link, finalLink
	// 'searchSecFilingsCompanyName', // Searches for SEC filing company information by company name. (company) -> symbol, name, cik, sicCode, industryTitle, businessAddress, phoneNumber
	// 'searchSecFilingsCompanyBySymbol', // Searches for SEC filing company information by stock symbol. (symbol) -> symbol, name, cik, sicCode, industryTitle, businessAddress, phoneNumber
	// 'searchSecFilingsCompanyByCik', // Searches for SEC filing company information by CIK. (cik) -> symbol, name, cik, sicCode, industryTitle, businessAddress, phoneNumber
	// 'secCompanyFullProfile', // Retrieves a full SEC company profile. (options (symbol, cik)) -> symbol, cik, registrantName, sicCode, sicDescription, sicGroup, isin, businessAddress, mailingAddress, phoneNumber, postalCode, city, state, country, description, ceo, website, exchange, stateLocation, stateOfIncorporation, fiscalYearEnd, ipoDate, employees, secFilingsUrl, taxIdentificationNumber, fiftyTwoWeekRange, isActive, assetType, openFigiComposite, priceCurrency, marketSector, securityType, isEtf, isAdr, isFund
	// 'industryClassificationList', // Retrieves a list of industry classifications (SIC codes and titles). (options (industryTitle, sicCode)) -> office, sicCode, industryTitle
	// 'searchIndustryClassification', // Searches for industry classification details for companies. (options (symbol, cik, sicCode)) -> symbol, name, cik, sicCode, industryTitle, businessAddress, phoneNumber
	// 'allIndustryClassification', // Retrieves all industry classification data for companies. (options (page, limit)) -> symbol, name, cik, sicCode, industryTitle, businessAddress, phoneNumber

	// SENATE AND HOUSE TRADING
	'latestSenateFinancialDisclosures', // Retrieves the latest financial disclosures from U.S. Senate members. (options (page, limit)) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD
	'latestHouseFinancialDisclosures', // Retrieves the latest financial disclosures from U.S. House members. (options (page, limit)) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD
	'senateTradingActivity', // Retrieves trading activity by U.S. Senators for a specific stock symbol. (symbol) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD
	'senateTradesByName', // Retrieves trading activity by U.S. Senators filtered by Senator's name. (name) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD
	'houseTrades', // Retrieves trading activity by U.S. House members for a specific stock symbol. (symbol) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD
	'houseTradesByName', // Retrieves trading activity by U.S. House members filtered by member's name. (name) -> symbol, disclosureDate, transactionDate, firstName, lastName, office, district, owner, assetDescription, assetType, type, amount, comment, link, capitalGainsOver200USD

	// BULK DATA
	// 'bulkCompanyProfile', // Retrieves company profile data in bulk. (part) -> symbol, price, marketCap, beta, lastDividend, range, change, changePercentage, volume, averageVolume, companyName, currency, cik, isin, cusip, exchangeFullName, exchange, industry, website, description, ceo, sector, country, fullTimeEmployees, phone, address, city, state, zip, image, ipoDate, defaultImage, isEtf, isActivelyTrading, isAdr, isFund
	// 'bulkStockRating', // Retrieves stock rating data in bulk. (No parameters.) -> symbol, date, rating, ratingRecommendation, ratingDetailsDCFRecommendation, ratingDetailsROERecommendation, ratingDetailsROARecommendation, ratingDetailsDERecommendation, ratingDetailsPERecommendation, ratingDetailsPBRecommendation
	// 'bulkDcfValuations', // Retrieves DCF valuations in bulk. (No parameters.) -> symbol, date, discountedCashFlow, dcfPercentDiff
	// 'bulkFinancialScores', // Retrieves financial scores in bulk. (No parameters.) -> symbol, reportedCurrency, altmanZScore, piotroskiScore, workingCapital, totalAssets, retainedEarnings, ebit, marketCap, totalLiabilities, revenue
	// 'bulkPriceTargetSummary', // Retrieves price target summaries in bulk. (No parameters.) -> symbol, lastMonth, lastMonthAvgPT, lastMonthAvgPTPercentDif, lastQuarter, lastQuarterAvgPT, lastQuarterAvgPTPercentDif, lastYear, lastYearAvgPT, lastYearAvgPTPercentDif, allTime, allTimeAvgPT, allTimeAvgPTPercentDif, publishers
	// 'bulkEtfHolder', // Retrieves ETF holder data in bulk. (part) -> symbol, asset, name, isin, securityCusip, sharesNumber, weightPercentage, marketValue, updatedAt, updated
	// 'bulkUpgradesDowngradesConsensus', // Retrieves upgrades/downgrades consensus data in bulk. (No parameters.) -> symbol, strongBuy, buy, hold, sell, strongSell, consensus
	// 'bulkKeyMetricsTtm', // Retrieves Key Metrics TTM data in bulk. (No parameters.) -> symbol, marketCap, marketCapTTM, enterpriseValueTTM, evToSalesTTM, evToOperatingCashFlowTTM, evToFreeCashFlowTTM, evToEBITDATTM, netDebtToEBITDATTM, currentRatioTTM, incomeQualityTTM, grahamNumberTTM, grahamNetNetTTM, taxBurdenTTM, interestBurdenTTM, workingCapitalTTM, investedCapitalTTM, returnOnAssetsTTM, operatingReturnOnAssetsTTM, returnOnTangibleAssetsTTM, returnOnEquityTTM, returnOnInvestedCapitalTTM, returnOnCapitalEmployedTTM, earningsYieldTTM, freeCashFlowYieldTTM, capexToOperatingCashFlowTTM, capexToDepreciationTTM, capexToRevenueTTM, salesGeneralAndAdministrativeToRevenueTTM, researchAndDevelopementToRevenueTTM, stockBasedCompensationToRevenueTTM, intangiblesToTotalAssetsTTM, averageReceivablesTTM, averagePayablesTTM, averageInventoryTTM, daysOfSalesOutstandingTTM, daysOfPayablesOutstandingTTM, daysOfInventoryOutstandingTTM, operatingCycleTTM, cashConversionCycleTTM, freeCashFlowToEquityTTM, freeCashFlowToFirmTTM, tangibleAssetValueTTM, netCurrentAssetValueTTM
	// 'bulkRatiosTtm', // Retrieves Ratios TTM data in bulk. (No parameters.) -> symbol, grossProfitMarginTTM, ebitMarginTTM, ebitdaMarginTTM, operatingProfitMarginTTM, pretaxProfitMarginTTM, continuousOperationsProfitMarginTTM, netProfitMarginTTM, bottomLineProfitMarginTTM, receivablesTurnoverTTM, payablesTurnoverTTM, inventoryTurnoverTTM, fixedAssetTurnoverTTM, assetTurnoverTTM, currentRatioTTM, quickRatioTTM, solvencyRatioTTM, cashRatioTTM, priceToEarningsRatioTTM, priceToEarningsGrowthRatioTTM, forwardPriceToEarningsGrowthRatioTTM, priceToBookRatioTTM, priceToSalesRatioTTM, priceToFreeCashFlowRatioTTM, priceToOperatingCashFlowRatioTTM, debtToAssetsRatioTTM, debtToEquityRatioTTM, debtToCapitalRatioTTM, longTermDebtToCapitalRatioTTM, financialLeverageRatioTTM, workingCapitalTurnoverRatioTTM, operatingCashFlowRatioTTM, operatingCashFlowSalesRatioTTM, freeCashFlowOperatingCashFlowRatioTTM, debtServiceCoverageRatioTTM, interestCoverageRatioTTM, shortTermOperatingCashFlowCoverageRatioTTM, operatingCashFlowCoverageRatioTTM, capitalExpenditureCoverageRatioTTM, dividendPaidAndCapexCoverageRatioTTM, dividendPayoutRatioTTM, dividendYieldTTM, dividendYieldPercentageTTM, enterpriseValueTTM, revenuePerShareTTM, netIncomePerShareTTM, interestDebtPerShareTTM, cashPerShareTTM, bookValuePerShareTTM, tangibleBookValuePerShareTTM, shareholdersEquityPerShareTTM, operatingCashFlowPerShareTTM, capexPerShareTTM, freeCashFlowPerShareTTM, netIncomePerEBTTTM, ebtPerEbitTTM, priceToFairValueTTM, debtToMarketCapTTM, effectiveTaxRateTTM, enterpriseValueMultipleTTM
	// 'bulkStockPeers', // Retrieves stock peers data in bulk. (No parameters.) -> symbol, peers
	// 'bulkEarningsSurprises', // Retrieves earnings surprises data in bulk for a specific year. (year) -> symbol, date, epsActual, epsEstimated, lastUpdated
	// 'bulkIncomeStatement', // Retrieves income statements in bulk for a specific year and period. (options (year, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, revenue, costOfRevenue, grossProfit, researchAndDevelopmentExpenses, generalAndAdministrativeExpenses, sellingAndMarketingExpenses, sellingGeneralAndAdministrativeExpenses, otherExpenses, operatingExpenses, costAndExpenses, netInterestIncome, interestIncome, interestExpense, depreciationAndAmortization, ebitda, ebit, nonOperatingIncomeExcludingInterest, operatingIncome, totalOtherIncomeExpensesNet, incomeBeforeTax, incomeTaxExpense, netIncomeFromContinuingOperations, netIncomeFromDiscontinuedOperations, otherAdjustmentsToNetIncome, netIncome, netIncomeDeductions, bottomLineNetIncome, eps, epsDiluted, weightedAverageShsOut, weightedAverageShsOutDil
	// 'bulkIncomeStatementGrowth', // Retrieves income statement growth data in bulk for a specific year and period. (options (year, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthRevenue, growthCostOfRevenue, growthGrossProfit, growthGrossProfitRatio, growthResearchAndDevelopmentExpenses, growthGeneralAndAdministrativeExpenses, growthSellingAndMarketingExpenses, growthOtherExpenses, growthOperatingExpenses, growthCostAndExpenses, growthInterestIncome, growthInterestExpense, growthDepreciationAndAmortization, growthEBITDA, growthOperatingIncome, growthIncomeBeforeTax, growthIncomeTaxExpense, growthNetIncome, growthEPS, growthEPSDiluted, growthWeightedAverageShsOut, growthWeightedAverageShsOutDil, growthEBIT, growthNonOperatingIncomeExcludingInterest, growthNetInterestIncome, growthTotalOtherIncomeExpensesNet, growthNetIncomeFromContinuingOperations, growthOtherAdjustmentsToNetIncome, growthNetIncomeDeductions
	// 'bulkBalanceSheetStatement', // Retrieves balance sheet statements in bulk for a specific year and period. (options (year, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, cashAndCashEquivalents, shortTermInvestments, cashAndShortTermInvestments, netReceivables, accountsReceivables, otherReceivables, inventory, prepaids, otherCurrentAssets, totalCurrentAssets, propertyPlantEquipmentNet, goodwill, intangibleAssets, goodwillAndIntangibleAssets, longTermInvestments, taxAssets, otherNonCurrentAssets, totalNonCurrentAssets, otherAssets, totalAssets, totalPayables, accountPayables, otherPayables, accruedExpenses, shortTermDebt, capitalLeaseObligationsCurrent, taxPayables, deferredRevenue, otherCurrentLiabilities, totalCurrentLiabilities, longTermDebt, deferredRevenueNonCurrent, deferredTaxLiabilitiesNonCurrent, otherNonCurrentLiabilities, totalNonCurrentLiabilities, otherLiabilities, capitalLeaseObligations, totalLiabilities, treasuryStock, preferredStock, commonStock, retainedEarnings, additionalPaidInCapital, accumulatedOtherComprehensiveIncomeLoss, otherTotalStockholdersEquity, totalStockholdersEquity, totalEquity, minorityInterest, totalLiabilitiesAndTotalEquity, totalInvestments, totalDebt, netDebt
	// 'bulkBalanceSheetStatementGrowth', // Retrieves balance sheet statement growth data in bulk for a specific year and period. (options (year, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthCashAndCashEquivalents, growthShortTermInvestments, growthCashAndShortTermInvestments, growthNetReceivables, growthInventory, growthOtherCurrentAssets, growthTotalCurrentAssets, growthPropertyPlantEquipmentNet, growthGoodwill, growthIntangibleAssets, growthGoodwillAndIntangibleAssets, growthLongTermInvestments, growthTaxAssets, growthOtherNonCurrentAssets, growthTotalNonCurrentAssets, growthOtherAssets, growthTotalAssets, growthAccountPayables, growthShortTermDebt, growthTaxPayables, growthDeferredRevenue, growthOtherCurrentLiabilities, growthTotalCurrentLiabilities, growthLongTermDebt, growthDeferredRevenueNonCurrent, growthDeferredTaxLiabilitiesNonCurrent, growthOtherNonCurrentLiabilities, growthTotalNonCurrentLiabilities, growthOtherLiabilities, growthTotalLiabilities, growthPreferredStock, growthCommonStock, growthRetainedEarnings, growthAccumulatedOtherComprehensiveIncomeLoss, growthOthertotalStockholdersEquity, growthTotalStockholdersEquity, growthMinorityInterest, growthTotalEquity, growthTotalLiabilitiesAndStockholdersEquity, growthTotalInvestments, growthTotalDebt, growthNetDebt, growthAccountsReceivables, growthOtherReceivables, growthPrepaids, growthTotalPayables, growthOtherPayables, growthAccruedExpenses, growthCapitalLeaseObligationsCurrent, growthAdditionalPaidInCapital, growthTreasuryStock
	// 'bulkCashFlowStatement', // Retrieves cash flow statements in bulk for a specific year and period. (options (year, period)) -> date, symbol, reportedCurrency, cik, filingDate, acceptedDate, fiscalYear, period, netIncome, depreciationAndAmortization, deferredIncomeTax, stockBasedCompensation, changeInWorkingCapital, accountsReceivables, inventory, accountsPayables, otherWorkingCapital, otherNonCashItems, netCashProvidedByOperatingActivities, investmentsInPropertyPlantAndEquipment, acquisitionsNet, purchasesOfInvestments, salesMaturitiesOfInvestments, otherInvestingActivities, netCashProvidedByInvestingActivities, netDebtIssuance, longTermNetDebtIssuance, shortTermNetDebtIssuance, netStockIssuance, netCommonStockIssuance, commonStockIssuance, commonStockRepurchased, netPreferredStockIssuance, netDividendsPaid, commonDividendsPaid, preferredDividendsPaid, otherFinancingActivities, netCashProvidedByFinancingActivities, effectOfForexChangesOnCash, netChangeInCash, cashAtEndOfPeriod, cashAtBeginningOfPeriod, operatingCashFlow, capitalExpenditure, freeCashFlow, incomeTaxesPaid, interestPaid
	// 'bulkCashFlowStatementGrowth', // Retrieves cash flow statement growth data in bulk for a specific year and period. (options (year, period)) -> symbol, date, fiscalYear, period, reportedCurrency, growthNetIncome, growthDepreciationAndAmortization, growthDeferredIncomeTax, growthStockBasedCompensation, growthChangeInWorkingCapital, growthAccountsReceivables, growthInventory, growthAccountsPayables, growthOtherWorkingCapital, growthOtherNonCashItems, growthNetCashProvidedByOperatingActivites, growthInvestmentsInPropertyPlantAndEquipment, growthAcquisitionsNet, growthPurchasesOfInvestments, growthSalesMaturitiesOfInvestments, growthOtherInvestingActivites, growthNetCashUsedForInvestingActivites, growthDebtRepayment, growthCommonStockIssued, growthCommonStockRepurchased, growthDividendsPaid, growthOtherFinancingActivites, growthNetCashUsedProvidedByFinancingActivities, growthEffectOfForexChangesOnCash, growthNetChangeInCash, growthCashAtEndOfPeriod, growthCashAtBeginningOfPeriod, growthOperatingCashFlow, growthCapitalExpenditure, growthFreeCashFlow, growthNetDebtIssuance, growthLongTermNetDebtIssuance, growthShortTermNetDebtIssuance, growthNetStockIssuance, growthPreferredDividendsPaid, growthIncomeTaxesPaid, growthInterestPaid
	// 'bulkEod', // Retrieves end-of-day (EOD) stock price data in bulk for a specific date. (date) -> symbol, date, open, low, high, close, adjClose, volume
])
