const allCategories = {
	search: [
		'searchSymbol',
		'searchName',
		// 'searchCik',
		// 'searchCusip',
		// 'searchIsin',
		// 'stockScreener',
		// 'searchExchangeVariants',
		'latestWebSearch', // NOTE: internal
	],
	directory: [
		// 'listCompanySymbols',
		// 'listFinancialStatementSymbols',
		// 'listCik',
		// 'listSymbolChanges',
		// 'listEtfSymbol',
		// 'listActivelyTrading',
		// 'availableExchanges',
		// 'availableSectors',
		// 'availableIndustries',
		// 'availableCountries',
	],
	company: [
		'companyProfile',
		// 'companyProfileByCik',
		// 'companyNotes',
		'stockPeers',
		// 'delistedCompanies',
		'companyEmployeeCount',
		'historicalCompanyEmployeeCount',
		'companyMarketCap',
		// 'batchMarketCap',
		'historicalMarketCap',
		'companySharesFloat',
		// 'allSharesFloat',
		// 'latestMergersAcquisitions',
		'searchMergersAcquisitions',
		'companyExecutives',
		'executiveCompensation',
		'executiveCompensationBenchmark',
	],
	calendar: [
		'companyDividends',
		// 'dividendsCalendar',
		'companyEarningsReports',
		// 'earningsCalendar',
		// 'iposCalendar',
		// 'ipoDisclosures',
		// 'ipoProspectus',
		// 'stockSplitDetails',
		// 'stockSplitsCalendar',
	],
	financialStatements: [
		'incomeStatement',
		'balanceSheetStatement',
		'cashFlowStatement',
		// 'latestFinancialStatements',
		'incomeStatementTtm',
		'balanceSheetStatementTtm',
		'cashFlowStatementTtm',
		'keyMetrics',
		'financialRatios',
		'keyMetricsTtm',
		'financialRatiosTtm',
		'financialScores',
		'ownerEarnings',
		'enterpriseValues',
		'incomeStatementGrowth',
		'balanceSheetStatementGrowth',
		'cashFlowStatementGrowth',
		'financialStatementGrowth',
		// 'financialReportsDates',
		// 'financialReportJson',
		// 'financialReportXlsx',
		'revenueProductSegmentation',
		'revenueGeographicSegmentation',
		// 'asReportedIncomeStatements',
		// 'asReportedBalanceStatements',
		// 'asReportedCashFlowStatements',
		// 'fullAsReportedFinancialStatements',
	],
	earningsTranscript: [
		// 'latestEarningTranscripts',
		// 'earningsTranscript',
		'earningsTranscriptDatesBySymbol',
		// 'earningsTranscriptList',
		'queryEarningsTranscript', // NOTE: internal
	],
	secFilings: [
		// 'latest8kSecFilings',
		// 'latestSecFilingsWithFinancials',
		// 'searchSecFilingsByFormType',
		// 'searchSecFilingsBySymbol',
		// 'searchSecFilingsByCik',
		// 'searchSecFilingsCompanyName',
		// 'searchSecFilingsCompanyBySymbol',
		// 'searchSecFilingsCompanyByCik',
		// 'secCompanyFullProfile',
		// 'industryClassificationList',
		// 'searchIndustryClassification',
		// 'allIndustryClassification',
		'searchSecFilings', // NOTE: internal
		'queryFilingDocument', // NOTE: internal
	],
	discountedCashFlow: ['dcfValuation', 'leveredDcfValuation', 'dcfAnalysis', 'dcfLeveredAnalysis'],
	chart: [
		// 'stockChartLight',
		'stockChartFull',
		// 'unadjustedStockChart',
		// 'dividendAdjustedStockChart',
		// 'historicalIntradayChart',
		// 'stockChart1Min',
		// 'stockChart5Min',
		// 'stockChart15Min',
		// 'stockChart30Min',
		// 'stockChart1Hour',
		// 'stockChart4Hour',
	],
	quote: [
		'stockQuote',
		'stockQuoteShort',
		'aftermarketTrade',
		'aftermarketQuote',
		'stockPriceChange',
		// 'stockBatchQuote',
		// 'stockBatchQuoteShort',
		// 'batchAftermarketTrade',
		// 'batchAftermarketQuote',
		'exchangeStockQuotes',
		'mutualFundQuotes',
		'etfQuotes',
	],
	indexes: [
		// 'indexesList',
		'indexQuote',
		// 'indexQuoteShort',
		// 'allIndexQuotes',
		// 'indexChartLight',
		'indexChartFull',
		// 'indexChart1Min',
		// 'indexChart5Min',
		// 'indexChart1Hour',
		// 'sp500Constituents',
		// 'nasdaqConstituents',
		// 'dowJonesConstituents',
		// 'historicalSp500Constituents',
		// 'historicalNasdaqConstituents',
		// 'historicalDowJonesConstituents',
	],
	commodity: [
		// 'commoditiesList',
		'commodityQuote',
		// 'commodityQuoteShort',
		// 'allCommoditiesQuotes',
		// 'commodityChartLight',
		'commodityChartFull',
		// 'commodityChart1Min',
		// 'commodityChart5Min',
		// 'commodityChart1Hour',
	],
	crypto: [
		// 'cryptocurrencyList',
		// 'cryptocurrencyQuote',
		// 'cryptocurrencyQuoteShort',
		// 'allCryptocurrenciesQuotes',
		// 'cryptocurrencyChartLight',
		// 'cryptocurrencyChartFull',
		// 'cryptocurrencyChart1Min',
		// 'cryptocurrencyChart5Min',
		// 'cryptocurrencyChart1Hour',
	],
	forex: [
		// 'forexList',
		// 'forexQuote',
		// 'forexQuoteShort',
		// 'allForexQuotes',
		// 'forexChartLight',
		// 'forexChartFull',
		// 'forexChart1Min',
		// 'forexChart5Min',
		// 'forexChart1Hour',
	],
	commitmentOfTraders: ['cotReport', 'cotAnalysis', 'cotReportList'],
	technicalIndicators: [
		'simpleMovingAverage',
		'exponentialMovingAverage',
		'weightedMovingAverage',
		'doubleExponentialMovingAverage',
		'tripleExponentialMovingAverage',
		'relativeStrengthIndex',
		'standardDeviation',
		'williamsPercentR',
		'averageDirectionalIndex',
	],
	analyst: [
		'financialEstimates',
		'ratingsSnapshot',
		'historicalRatings',
		'priceTargetSummary',
		'priceTargetConsensus',
		'priceTargetNews',
		// 'latestPriceTargetNews',
		// 'historicalStockGrades',
		'stockGrades',
		'stockGradeConsensus',
		'stockGradeNews',
		// 'latestStockGradeNews',
	],
	marketPerformance: [
		// 'marketSectorPerformanceSnapshot',
		// 'marketIndustryPerformanceSnapshot',
		// 'historicalMarketSectorPerformance',
		// 'historicalMarketIndustryPerformance',
		// 'marketSectorPESnapshot',
		// 'marketIndustryPESnapshot',
		// 'historicalMarketSectorPE',
		// 'historicalMarketIndustryPE',
		// 'biggestStockGainers',
		// 'biggestStockLosers',
		// 'topTradedStocks',
	],
	crowdfunding: [
		// 'latestCrowdfundingCampaigns',
		// 'searchCrowdfundingCampaigns',
		// 'crowdfundingCampaignsByCik',
		// 'latestEquityOfferingUpdates',
		// 'searchEquityOfferings',
		// 'equityOfferingsByCik',
	],
	marketHours: [
		// 'exchangeMarketHours',
		// 'allExchangeMarketHours',
	],
	news: [
		// 'fmpArticles',
		// 'generalNews',
		// 'pressReleases',
		// 'stockNews',
		// 'cryptoNews',
		// 'forexNews',
		// 'searchPressReleases',
		// 'searchStockNews',
		// 'searchCryptoNews',
		// 'searchForexNews',
	],
	insiderTrades: [
		'latestInsiderTrades',
		'searchInsiderTrades',
		'searchInsiderTradesByReportingName',
		'allInsiderTransactionTypes',
		'insiderTradeStatistics',
		'acquisitionOwnership',
	],
	form13f: [
		// 'latestInstitutionalOwnershipFilings',
		// 'secFilingsExtract',
		// 'form13FFilingDates',
		'filingsExtractAnalyticsByHolder',
		'holderPerformanceSummary',
		'holdersIndustryBreakdown',
		'positionsSummary',
		'industryPerformanceSummary',
	],
	senateAndHouseTrading: [
		'latestSenateFinancialDisclosures',
		'latestHouseFinancialDisclosures',
		'senateTradingActivity',
		'senateTradesByName',
		'houseTrades',
		'houseTradesByName',
	],
	economics: [
		'treasuryRates',
		'economicIndicators',
		'economicCalendar',
		// 'marketRiskPremium',
	],
	etfAndMutualFund: [
		'etfFundHoldings',
		'etfFundInfo',
		'etfFundCountryAllocation',
		// 'etfAssetExposure',
		// 'etfSectorWeighting',
		'mutualFundEtfLatestDisclosures',
		'mutualFundDisclosures',
		'searchMutualFundEtfDisclosuresByName',
		'fundEtfDisclosuresByDate',
	],
	esg: [
		// 'esgDisclosures',
		// 'esgRatings',
		// 'esgBenchmark',
	],
	bulkData: [
		// 'bulkCompanyProfile',
		// 'bulkStockRating',
		// 'bulkDcfValuations',
		// 'bulkFinancialScores',
		// 'bulkPriceTargetSummary',
		// 'bulkEtfHolder',
		// 'bulkUpgradesDowngradesConsensus',
		// 'bulkKeyMetricsTtm',
		// 'bulkRatiosTtm',
		// 'bulkStockPeers',
		// 'bulkEarningsSurprises',
		// 'bulkIncomeStatement',
		// 'bulkIncomeStatementGrowth',
		// 'bulkBalanceSheetStatement',
		// 'bulkBalanceSheetStatementGrowth',
		// 'bulkCashFlowStatement',
		// 'bulkCashFlowStatementGrowth',
		// 'bulkEod',
	],
} as const

type FilterEmptyArrays<T> = {
	[K in keyof T as T[K] extends readonly [] ? never : K]: T[K]
}

export const categories: FilterEmptyArrays<typeof allCategories> = Object.fromEntries(
	Object.entries(allCategories).filter(([_, value]) => value.length > 0),
) as FilterEmptyArrays<typeof allCategories>
